export const sg1000JPNTitles = [
    "Bank Panic",
    "Black Onyx",
    "Bomb Jack",
    "Borderline",
    "C_So!",
    "Castle",
    "Chack'n Pop",
    "Champion Baseball",
    "Champion Billiards",
    "Champion Boxing",
    "Champion Golf",
    "Champion Ice Hockey",
    "Champion Kendou",
    "Champion Pro Wrestling",
    "Champion Soccer",
    "Champion Tennis",
    "Championship Lode Runner",
    "Choplifter",
    "Congo Bongo",
    "Dokidoki Penguin Land",
    "Dragon Wang",
    "Drol",
    "Elevator Action",
    "Exerion",
    "Flicky",
    "GP World",
    "Girl's Garden",
    "Golgo 13",
    "Gulkave",
    "Guzzler",
    "H.E.R.O.",
    "Hang-On II",
    "Home Mahjong",
    "Hustle Chumy",
    "Hyper Sports",
    "James Bond 007",
    "Lode Runner",
    "Mahjong",
    "Monaco GP",
    "N-Sub",
    "Ninja Princess",
    "Orguss",
    "Pacar",
    "Pachinko II",
    "Pachinko",
    "Pitfall II - The Lost Caverns",
    "Pop Flamer",
    "Q-bert",
    "Rock n' Bolt",
    "Safari Hunting",
    "Safari Race",
    "Sega Flipper",
    "Sega-Galaga",
    "Serizawa Hachidan no Tsumeshogi",
    "Shinnyushain Tooru Kun",
    "Sindbad Mystery",
    "Soukoban",
    "Space Invaders",
    "Space Mountain",
    "Space Slalom",
    "Star Force",
    "Star Jacker",
    "Super Tank",
    "Wonder Boy",
    "Yamato",
    "Zaxxon",
    "Zippy Race",
    "Zoom 909"
]