export const sg32XNATitles = [
    "After Burner",
    "Amazing Spider-Man, The - Web of Fire",
    "BC Racers",
    "Blackthorne",
    "Brutal Unleashed - Above the Claw",
    "Cosmic Carnage",
    "Doom",
    "Golf Magazine 36 Great Holes Starring Fred Couples",
    "Knuckles' Chaotix",
    "Kolibri",
    "Metal Head",
    "Mortal Kombat II",
    "Motocross Championship",
    "NBA Jam Tournament Edition",
    "NFL Quarterback Club",
    "Pitfall - The Mayan Adventure",
    "Primal Rage",
    "RBI Baseball '95",
    "Shadow Squadron",
    "Space Harrier",
    "Star Trek Starfleet Academy - Starship Bridge Simulator",
    "Star Wars Arcade",
    "T-Mek",
    "Tempo",
    "Toughman Contest",
    "Virtua Fighter",
    "Virtua Racing Deluxe",
    "WWF Raw",
    "WWF WrestleMania - The Arcade Game",
    "World Series Baseball Starring Deion Sanders",
    "Zaxxon's Motherbase 2000"
]

export const sg32XEUTitles = [
    "After Burner Complete",
    "Cosmic Carnage",
    "Darxide",
    "Doom",
    "FIFA Soccer '96",
    "Golf Magazine 36 Great Holes Starring Fred Couples",
    "Knuckles' Chaotix",
    "Kolibri",
    "Metal Head",
    "Mortal Kombat II",
    "Motocross Championship",
    "NBA Jam Tournament Edition",
    "NFL Quarterback Club",
    "Primal Rage",
    "Shadow Squadron ~ Stellar Assault",
    "Space Harrier",
    "Star Wars Arcade",
    "T-Mek",
    "Toughman Contest",
    "Virtua Fighter",
    "Virtua Racing Deluxe",
    "WWF Raw",
    "Zaxxon's Motherbase 2000"
]

export const sg32XJPNTitles = [
    "After Burner Complete ~ After Burner",
    "Chaotix ~ Knuckles' Chaotix",
    "Cyber Brawl ~ Cosmic Carnage",
    "Doom",
    "Golf Magazine 36 Great Holes Starring Fred Couples",
    "Metal Head",
    "Mortal Kombat II",
    "NBA Jam - Tournament Edition",
    "NFL Quarterback Club",
    "Parasquad ~ Zaxxon's Motherbase 2000",
    "Sangokushi IV",
    "Space Harrier",
    "Star Wars Arcade",
    "Stellar Assault",
    "Tempo",
    "Virtua Fighter",
    "Virtua Racing Deluxe",
    "WWF Raw"
]