export const sgCDNATitles = [
    "3 Ninjas Kick Back - Hook",
    "3 Ninjas Kick Back",
    "AH-3 Thunderstrike",
    "AX-101",
    "Advanced Dungeons & Dragons - Eye of the Beholder",
    "Adventures of Batman & Robin",
    "Adventures of Willy Beamish",
    "After Burner III",
    "Amazing Spider-Man vs. The Kingpin",
    "Android Assault - The Revenge of Bari-Arm",
    "BC Racers",
    "Batman Returns",
    "Battlecorps",
    "Bill Walsh College Football",
    "Black Hole Assault",
    "Bouncers",
    "Bram Stoker's Dracula",
    "Brutal - Paws of Fury",
    "Cadillacs and Dinosaurs - The Second Cataclysm",
    "Championship Soccer '94",
    "Chuck Rock II - Son of Chuck",
    "Chuck Rock",
    "Cliffhanger",
    "Cobra Command",
    "Compton's Interactive Encyclopedia",
    "Corpse Killer",
    "Crime Patrol",
    "Dark Wizard",
    "Demolition Man",
    "Double Switch",
    "Dracula Unleashed",
    "Dragon's Lair",
    "Dune",
    "Dungeon Explorer",
    "Dungeon Master 2 - Skullkeep",
    "ESPN Baseball Tonight",
    "ESPN NBA Hangtime '95",
    "ESPN National Hockey Night",
    "ESPN Sunday Night NFL",
    "Earthworm Jim - Special Edition",
    "Ecco - The Tides of Time",
    "Ecco the Dolphin",
    "Eternal Champions - Challenge from the Dark Side",
    "FIFA International Soccer",
    "Fahrenheit",
    "Fatal Fury Special",
    "Final Fight CD",
    "Flashback - The Quest for Identity",
    "Flink",
    "Formula One World Championship - Beyond the Limit",
    "Ground Zero Texas",
    "Heart of the Alien - Out of This World Parts I and II",
    "Heimdall",
    "Hook",
    "Iron Helix",
    "Jaguar XJ220",
    "Jeopardy!",
    "Joe Montana's NFL Football",
    "Jurassic Park",
    "Keio Flying Squadron",
    "Kids on Site",
    "Lawnmower Man",
    "Lethal Enforcers II - Gun Fighters",
    "Lethal Enforcers",
    "Links - The Challenge of Golf",
    "Loadstar - The Legend of Tully Bodine",
    "Lords of Thunder",
    "Lunar - Eternal Blue",
    "Lunar - The Silver Star",
    "Mad Dog McCree II - The Lost Gold",
    "Mad Dog McCree",
    "Make My Video - INXS",
    "Make My Video - Kriss Kross",
    "Make My Video - Marky Mark and the Funky Bunch",
    "Mansion of Hidden Souls",
    "Mary Shelley's Frankenstein",
    "Mary Shellys Frankenstein",
    "Masked Rider - Kamen Rider ZO",
    "MegaRace",
    "Mickey Mania - The Timeless Adventures of Mickey Mouse",
    "Microcosm",
    "Midnight Raiders",
    "Mighty Morphin Power Rangers",
    "Mortal Kombat",
    "My Paint - The Animated Paint Program",
    "NBA Jam",
    "NFL Football Trivia Challenge",
    "NFL's Greatest - San Francisco vs. Dallas 1978-1993",
    "NHL '94",
    "Night Trap",
    "Novastorm",
    "Panic!",
    "Penn & Teller - Smoke and Mirrors",
    "Pier Solar",
    "Pitfall - The Mayan Adventure",
    "Popful Mail",
    "Power Factory featuring C+C Music Factory",
    "Power Monger",
    "Prince of Persia",
    "Prize Fighter",
    "Puggsy",
    "RDF Global Conflict",
    "Racing Aces",
    "Radical Rex",
    "Revenge of the Ninja",
    "Revengers of Vengeance",
    "Rise of the Dragon",
    "Road Avenger",
    "Road Rash",
    "Robo Aleste",
    "Samurai Shodown",
    "San Diego Zoo Presents... The Animals!",
    "Secret Of Monkey Island",
    "Sega Classics Arcade Collection 4-in-1",
    "Sega Classics Arcade Collection 5-in-1",
    "Sewer Shark",
    "Shadow of the Beast II",
    "Sherlock Holmes - Consulting Detective Vol. II",
    "Sherlock Holmes - Consulting Detective",
    "Shining Force CD",
    "Silpheed",
    "Slam City with Scottie Pippen",
    "Snatcher",
    "Sol-Feace",
    "Sonic CD",
    "Soulstar",
    "Space Ace",
    "Space Adventure",
    "Star Wars Chess",
    "Star Wars Rebel Assault",
    "Starblade",
    "Stellar-Fire",
    "Super Strike Trilogy",
    "Supreme Warrior",
    "Surgical Strike (Brazil)",
    "Surgical Strike",
    "Terminator",
    "Third World War",
    "Time Gal",
    "Tomcat Alley",
    "Trivial Pursuit - Interactive Multimedia Game",
    "Ultraverse Prime (USA)",
    "Ultraverse Prime",
    "Vay",
    "Virtual VCR - The Colors of Modern Rock",
    "WWF Rage in the Cage",
    "Wheel of Fortune",
    "Who Shot Johnny Rock",
    "Wild Woody",
    "Wing Commander",
    "Wirehead",
    "Wolfchild",
    "Wonder Dog",
    "World Cup USA '94"
]

export const sgCDEUTitles = [
    "Adventures of Batman and Robin",
    "After Burner III",
    "Amazing Spider-Man vs. The Kingpin",
    "Animals!",
    "BC Racers",
    "Batman Returns",
    "Battlecorps",
    "Bill Walsh College Football",
    "Blackhole Assault",
    "Bloodshot ~ Battle Frenzy",
    "Brutal - Paws of Fury",
    "Chuck Rock II - Son of Chuck",
    "Chuck Rock",
    "Cobra Command",
    "Corpse Killer",
    "Double Switch",
    "Dracula Unleashed",
    "Dragon's Lair",
    "Dune",
    "Dungeon Explorer",
    "Dungeon Master II - Skullkeep",
    "ESPN Baseball Tonight",
    "Earthworm Jim - Special Edition",
    "Ecco - The Tides of Time",
    "Ecco the Dolphin",
    "Eternal Champions - Challenge from the Dark Side",
    "Eye of the Beholder",
    "FIFA International Soccer - Championship Edition",
    "Fahrenheit",
    "Fatal Fury Special",
    "Final Fight CD",
    "Flink",
    "Formula One World Championship - Beyond the Limit",
    "Ground Zero Texas",
    "Hook",
    "Jaguar XJ220",
    "Jurassic Park",
    "Keio Flying Squadron",
    "Kids on Site",
    "Lawnmower Man",
    "Lethal Enforcers II - Gun Fighters",
    "Lethal Enforcers.jpg",
    "Lethal Enforcers",
    "Lords of Thunder",
    "Make My Video - INXS",
    "Make My Video - Kris Kross",
    "Marko's Magic Football",
    "Mickey Mania",
    "Microcosm",
    "Midnight Raiders",
    "Mighty Morphin Power Rangers",
    "Mortal Kombat",
    "NBA Jam",
    "NHL Hockey '94",
    "Night Trap",
    "Novastorm",
    "Pitfall - The Mayan Adventure",
    "Power Factory featuring C+C Music Factory",
    "PowerMonger",
    "Prince of Persia",
    "Prize Fighter",
    "Puggsy",
    "Road Avenger",
    "Robo Aleste",
    "Samurai Shodown",
    "Sega Classics Arcade Collection - Limited Edition",
    "Sensible Soccer",
    "Sewer Shark",
    "Shadow of the Beast II",
    "Sherlock Holmes - Consulting Detective Vol. II",
    "Sherlock Holmes - Consulting Detective",
    "Shining Force CD",
    "Silpheed",
    "Slam City with Scottie Pippen",
    "Smurfs",
    "Snatcher",
    "Software Toolworks' Star Wars Chess",
    "Sol-Feace",
    "Sonic CD",
    "SoulStar",
    "Space Adventure - Cobra - The Legendary Bandit",
    "Star Wars - Rebel Assault",
    "Starblade",
    "Supreme Warrior",
    "Surgical Strike",
    "Syndicate",
    "Terminator",
    "Theme Park",
    "Thunderhawk",
    "Time Gal",
    "Tomcat Alley",
    "WWF - Rage in the Cage",
    "Wolfchild",
    "Wonder Dog",
    "World Cup USA '94",
    "Yumemi Mystery Mansion"
]

export const sgCDJPNTitles = [
    "A-Rank Thunder - Tanjou-hen",
    "AX-101",
    "After Armageddon Gaiden - Majuu Toushouden Eclipse",
    "After Burner III",
    "Aisle Lord",
    "Alshark",
    "Annett Futatabi",
    "Aoki Ookami to Shiroki Mejika - Genchou Hishi",
    "Arcus I, II, III",
    "Arslan Senki",
    "Bakuden - The Unbalanced Zone",
    "Bari-Arm",
    "Battle Fantasy",
    "Battlecorps",
    "Black Hole Assault",
    "Burai - Yatsudama no Yuushi Densetsu",
    "Captain Tsubasa",
    "Cosmic Fantasy Stories",
    "Cyborg 009",
    "Daihoushinden",
    "Dark Wizard - Yomigaeri Shiyami no Madoushi",
    "Death Bringer",
    "Dennin Aleste - Nobunaga and His Ninja Force",
    "Detonator Orgun",
    "Devastator",
    "Double Switch",
    "Dragon's Lair",
    "Dungeon Master II - Skullkeep",
    "Dynamic Country Club",
    "Earnest Evans",
    "Ecco the Dolphin CD",
    "Egawa Suguru no Super League CD",
    "Eye Of The Beholder",
    "F1 Circus CD",
    "Fahrenheit",
    "Final Fight CD",
    "Fresh Cleaner.jpg",
    "Game no Kandume Vol. 1",
    "Game no Kandume Vol. 2",
    "Garou Densetsu Special",
    "Genei Toshi - Illusion City",
    "Gyuwambler Jiko Chuushinha 2 - Gekitou! Tokyo Mahjongland Hen",
    "Heavenly Symphony - Formula One World Championship 1993",
    "Heavy Nova",
    "Heimdall",
    "IIIrd World War",
    "Ishii Hisaichi no Daiseikai",
    "Jaguar XJ220",
    "Jangou World Cup",
    "Jurassic Park",
    "Kamen Rider ZO",
    "Keiou Yuugekitai",
    "Lethal Enforcers II - The Western",
    "Lethal Enforcers",
    "Lunar - Eternal Blue",
    "Lunar - The Silver Star",
    "Mahou no Shoujo - Silky Lip",
    "Mega Schwarzschild",
    "Microcosm",
    "Might and Magic III - Isles of Terra",
    "Mortal Kombat Kanzenban",
    "NBA Jam",
    "Night Striker (Japan, Korea)",
    "Night Trap",
    "Ninja Warriors",
    "Nobunaga no Yabou - Haouden",
    "Nostalgia 1907",
    "Popful Mail",
    "Prince of Persia",
    "Prize Fighter",
    "Pro Yakyuu Super League CD",
    "Psychic Detective Series Vol. 3 - Aya",
    "Psychic Detective Series Vol. 4 - Orgel",
    "Quiz Scramble Special",
    "Quiz Tonosama no Yabou",
    "Ranma 1-2 - Byakuranaika",
    "Record of Lodoss War",
    "Rise of the Dragon - A Blade Hunter Mystery",
    "Road Blaster FX",
    "Sangokushi III",
    "Secret of Monkey Island",
    "Sega Classic Arcade Collection - Limited Edition",
    "Seima Densetsu 3x3 Eyes",
    "Seirei Shinseiki - Fhey Area",
    "Sengoku Denshou",
    "Shadow of the Beast II - Juushin no Jubaku",
    "Shadowrun",
    "Shin Megami Tensei",
    "Shining Force CD",
    "Silpheed",
    "SimEarth",
    "Sing!! Sega Game Music Presented by B. B. Queens",
    "Sol-Feace",
    "Sonic The Hedgehog CD",
    "SoulStar",
    "Star Wars - Rebel Assault",
    "Starblade",
    "Surgical Strike",
    "Switch",
    "Tenbu Mega CD Special",
    "Tenkafubu - Eiyuutachi no Houkou",
    "Thunder Storm FX",
    "Thunderhawk",
    "Time Gal",
    "Tomcat Alley",
    "Urusei Yatsura - Dear My Friends",
    "Vay - Ryuusei no Yoroi",
    "WWF Mania Tour - WWF - Rage in the Cage",
    "Wakusei Woodstock - Funky Horror Band",
    "Warau Salesman",
    "Wing Commander",
    "Winning Post",
    "Wolfchild",
    "Wonder Dog",
    "WonderMega Collection",
    "Yumemi Yakata no Monogatari",
    "Yumimi Mix"
]