export const sgGenNATitles = [
    "3 Ninjas Kick Back",
    "6-Pak",
    "688 Attack Sub",
    "AAAHH!!! Real Monsters",
    "ATP Tour Championship Tennis",
    "Action 52",
    "Addams Family",
    "Adventures of Batman & Robin",
    "Adventures of Mighty Max",
    "Adventures of Rocky and Bullwinkle and Friends",
    "Aero the Acro-Bat 2",
    "Aero the Acro-Bat",
    "Aerobiz Supersonic",
    "Aerobiz",
    "After Burner II",
    "Air Buster",
    "Air Diver",
    "Al Michaels Announces HardBall III",
    "Aladdin",
    "Alex Kidd in the Enchanted Castle",
    "Alien 3",
    "Alien Storm",
    "Alisia Dragoon",
    "Altered Beast",
    "American Gladiators",
    "Andre Agassi Tennis",
    "Animaniacs",
    "Aquatic Games Starring James Pond and the Aquabats",
    "Arcade Classics",
    "Arcade Legends Sega Mega Drive ~ Arcade Legends Sega Genesis ~ Mega Drive Play TV",
    "Arcade Legends Street Fighter II' - Special Champion Edition ~ Mega Drive Play TV 3",
    "Arch Rivals - The Arcade Game",
    "Arcus Odyssey",
    "Ariel the Little Mermaid",
    "Arnold Palmer Tournament Golf",
    "Arrow Flash",
    "Art Alive",
    "Art of Fighting",
    "Asterix and the Great Rescue",
    "Atomic Robo-Kid",
    "Atomic Runner",
    "Awesome Possum... ...Kicks Dr. Machino's Butt",
    "Ayrton Senna's Super Monaco GP II",
    "Back to the Future Part III",
    "Ballz 3D - Fighting at Its Ballziest ~ Ballz 3D - The Battle of the Ballz",
    "Barbie Super Model",
    "Bare Knuckle - Ikari no Tekken ~ Streets of Rage",
    "Barkley Shut Up and Jam 2",
    "Barkley Shut Up and Jam!",
    "Barney's Hide & Seek Game",
    "Bass Masters Classic - Pro Edition",
    "Bass Masters Classic",
    "Batman - Revenge of the Joker",
    "Batman - The Video Game",
    "Batman Forever",
    "Batman Returns",
    "Battle Squadron",
    "BattleTech - A Game of Armored Combat",
    "Battlemaster",
    "Battletoads-Double Dragon",
    "Battletoads",
    "Beast Wrestler",
    "Beauty and the Beast - Belle's Quest",
    "Beauty and the Beast - Roar of the Beast",
    "Beavis and Butt-Head",
    "Beggar Prince",
    "Berenstain Bears' Camping Adventure",
    "Best of the Best - Championship Karate",
    "Beyond Oasis",
    "Bible Adventures",
    "Bill Walsh College Football 95",
    "Bill Walsh College Football",
    "Bimini Run",
    "Bio Hazard Battle",
    "Blades of Vengeance",
    "Blaster Master 2",
    "Blockbuster World Video Game Championship II",
    "Blockout",
    "Bonkers",
    "Boogerman - A Pick and Flick Adventure",
    "Boxing Legends of the Ring",
    "Bram Stoker's Dracula",
    "Brett Hull Hockey 95",
    "Brutal - Paws of Fury",
    "Bubba 'N' Stix",
    "Bubble and Squeak",
    "Bubsy II",
    "Bubsy in - Claws Encounters of the Furred Kind",
    "Buck Rogers - Countdown to Doomsday",
    "Budokan - The Martial Spirit",
    "Bugs Bunny in Double Trouble",
    "Bulls Vs Lakers and the NBA Playoffs",
    "Bulls versus Blazers and the NBA Playoffs",
    "Burning Force",
    "Cadash (USA, Asia, Korea)",
    "Caesars Palace",
    "Cal Ripken Jr. Baseball",
    "Caliber.50",
    "California Games",
    "Captain America and the Avengers",
    "Cascade",
    "Castle of Illusion Starring Mickey Mouse",
    "Castlevania - Bloodlines",
    "Centurion - Defender of Rome",
    "Chakan",
    "Champions World Class Soccer",
    "Championship Bowling",
    "Championship Pool",
    "Championship Pro-Am",
    "Chase H.Q. II",
    "Chester Cheetah - Too Cool to Fool",
    "Chester Cheetah - Wild Wild Quest",
    "Chi Chi's Pro Challenge Golf",
    "Chiki Chiki Boys",
    "Chuck Rock II - Son of Chuck",
    "Chuck Rock",
    "ClayFighter",
    "Cliffhanger",
    "Clue",
    "Coach K College Basketball",
    "College Football USA 96",
    "College Football USA 97",
    "College Football's National Championship II",
    "College Football's National Championship",
    "College Slam",
    "Columns III",
    "Columns",
    "Combat Cars",
    "Comix Zone",
    "Contra - Hard Corps (USA, Korea)",
    "Cool Spot",
    "Cosmic Spacehead",
    "Crack Down",
    "CrossFire (Sample)",
    "CrossFire",
    "Crue Ball - Heavy Metal Pinball",
    "Crusader of Centy",
    "Crystal's Pony Tale",
    "CutThroat Island",
    "Cyber-Cop",
    "CyberBall",
    "Cyborg Justice",
    "DEcapAttack",
    "DJ Boy",
    "Dark Castle",
    "Dashin' Desperadoes",
    "David Crane's Amazing Tennis",
    "David Robinson's Supreme Court",
    "Davis Cup Tennis ~ Davis Cup World Tour",
    "Deadly Moves",
    "Death Duel",
    "Death and Return of Superman",
    "Demolition Man",
    "Desert Demolition Starring Road Runner and Wile E. Coyote",
    "Desert Strike - Return To The Gulf",
    "Devilish - The Next Possession",
    "Dick Tracy",
    "Dick Vitale's 'Awesome, Baby!' College Hoops",
    "Dino Land",
    "Dinosaur's Tale, A",
    "Doom Troopers",
    "Double Dragon 3 - The Arcade Game",
    "Double Dragon V - The Shadow Falls",
    "Double Dragon",
    "Double Dribble - The Playoff Edition",
    "Dr. Robotnik's Mean Bean Machine",
    "Dragon - The Bruce Lee Story",
    "Dragon's Fury",
    "Dragon's Revenge",
    "Dune - The Battle For Arrakis",
    "Dungeons & Dragons - Warriors of the Eternal Sun",
    "Dynamite Duke",
    "Dynamite Headdy",
    "ESPN Baseball Tonight",
    "ESPN National Hockey Night",
    "ESPN Speed World",
    "ESPN Sunday Night NFL",
    "Earnest Evans",
    "Earth Defense ~ Earth Defend",
    "Earthworm Jim 2",
    "Earthworm Jim",
    "Ecco - The Tides of Time",
    "Ecco Jr.",
    "Ecco the Dolphin",
    "El.Viento",
    "Elemental Master",
    "Eternal Champions",
    "Evander Holyfield's 'Real Deal' Boxing",
    "Ex-Mutants",
    "Exile",
    "Exo Squad",
    "Exodus - Journey to the Promised Land",
    "F-117 Night Storm",
    "F-15 Strike Eagle II (Sample)",
    "F-15 Strike Eagle II",
    "F-22 Interceptor - Advanced Tactical Fighter",
    "FIFA International Soccer",
    "FIFA Soccer 95",
    "FIFA Soccer 96",
    "FIFA Soccer 97",
    "FZ Senki Axis ~ Final Zone",
    "Faery Tale Adventure",
    "Family Feud",
    "Fantasia",
    "Fantastic Dizzy",
    "Fatal Fury 2 (USA, Korea)",
    "Fatal Fury",
    "Fatal Labyrinth",
    "Fatal Rewind",
    "Ferrari Grand Prix Challenge",
    "Fighting Masters",
    "Fire Shark",
    "Flashback - The Quest for Identity (En,Fr)",
    "Flicky",
    "Flintstones",
    "Foreman for Real",
    "Forgotten Worlds",
    "Formula One",
    "Frank Thomas Big Hurt Baseball",
    "Frogger",
    "Fun 'N' Games",
    "Funny World & Balloon Boy",
    "G-LOC - Air Battle",
    "Gadget Twins",
    "Gaiares",
    "Gain Ground",
    "Game Genie",
    "Garfield - Caught in the Act",
    "Gargoyles",
    "Garry Kitchen's Super Battletank - War in the Gulf",
    "Gauntlet IV",
    "Gemfire",
    "General Chaos",
    "Generations Lost",
    "Genghis Khan II - Clan of the Gray Wolf",
    "George Foreman's KO Boxing",
    "Ghostbusters",
    "Gods",
    "Golden Axe II",
    "Golden Axe",
    "Goofy's Hysterical History Tour",
    "Granada",
    "Great Circus Mystery Starring Mickey & Minnie",
    "Great Waldo Search",
    "Greatest Heavyweights",
    "Greendog - The Beached Surfer Dude!",
    "Grind Stormer",
    "Growl",
    "Gunstar Heroes",
    "Hard Drivin'",
    "HardBall '94",
    "HardBall '95",
    "HardBall!",
    "Haunting Starring Polterguy",
    "Head-On Soccer",
    "Heavy Nova",
    "Hellfire",
    "Herzog Zwei",
    "High Seas Havoc",
    "Hit the Ice - VHL - The Official Video Hockey League",
    "Home Alone 2 - Lost in New York",
    "Home Alone",
    "Hook",
    "Humans",
    "IMG International Tour Tennis",
    "Immortal",
    "Incredible Crash Dummies",
    "Incredible Hulk",
    "Indiana Jones and the Last Crusade",
    "Insector X",
    "Instruments of Chaos Starring Young Indiana Jones",
    "Ishido - The Way of Stones",
    "Izzy's Quest for the Olympic Rings",
    "Jack Nicklaus' Power Challenge Golf",
    "James 'Buster' Douglas Knockout Boxing",
    "James Bond 007 - The Duel",
    "James Pond - Underwater Agent",
    "James Pond 3",
    "James Pond II - Codename - Robocod",
    "Jammit",
    "Jennifer Capriati Tennis",
    "Jeopardy! - Deluxe Edition",
    "Jeopardy! - Sports Edition",
    "Jeopardy!",
    "Jerry Glanville's Pigskin Footbrawl",
    "Jewel Master",
    "Joe & Mac",
    "Joe Montana Football",
    "Joe Montana II Sports Talk Football",
    "John Madden Football '92",
    "John Madden Football '93",
    "John Madden Football - Championship Edition",
    "John Madden Football",
    "Jordan Vs Bird",
    "Joshua & The Battle of Jericho",
    "Journey from Darkness - Strider Returns",
    "Judge Dredd",
    "Junction",
    "Jungle Book",
    "Jungle Strike",
    "Jurassic Park - Rampage Edition",
    "Jurassic Park",
    "Justice League Task Force",
    "Ka-Ge-Ki - Fists of Steel",
    "Kawasaki Superbike Challenge",
    "Kid Chameleon",
    "King Salmon - The Big Catch",
    "King of the Monsters 2",
    "King of the Monsters",
    "King's Bounty - The Conqueror's Quest",
    "Klax (Tengen)",
    "Krusty's Super Fun House",
    "LHX Attack Chopper",
    "La Russa Baseball 95",
    "Lakers versus Celtics and the NBA Playoffs",
    "Landstalker",
    "Last Action Hero",
    "Last Battle",
    "Lawnmower Man",
    "Legend of Galahad ~ Galahad",
    "Legend of Wukong",
    "Lemmings 2 - The Tribes",
    "Lemmings",
    "Lethal Enforcers II - Gun Fighters",
    "Lethal Enforcers",
    "Liberty or Death",
    "Light Crusader",
    "Lightening Force - Quest for the Darkstar",
    "Lion King",
    "Lost Vikings",
    "Lost World - Jurassic Park",
    "Lotus II",
    "Lotus Turbo Challenge",
    "M-1 Abrams Battle Tank",
    "MLBPA Baseball",
    "MUSHA - Metallic Uniframe Super Hybrid Armor",
    "Madden NFL '94",
    "Madden NFL 95",
    "Madden NFL 96",
    "Madden NFL 97",
    "Madden NFL 98",
    "Magic Girl featuring Ling Ling the Little Witch",
    "Magic School Bus - Space Exploration Game",
    "Mallet Legend's Whac-a-Critter ~ Mallet Legend",
    "Marble Madness",
    "Mario Andretti Racing",
    "Mario Lemieux Hockey",
    "Marko",
    "Marsupilami",
    "Marvel Land",
    "Mary Shelley's Frankenstein",
    "Master of Monsters",
    "Math Blaster - Episode 1",
    "Mazin Saga - Mutant Fighter",
    "McDonald's Treasure Land Adventure",
    "Mega Bomberman",
    "Mega Turrican",
    "Menacer 6-Game Cartridge",
    "Michael Jackson's Moonwalker",
    "Mick & Mack as the Global Gladiators",
    "Mickey Mania - The Timeless Adventures of Mickey Mouse",
    "Mickey's Ultimate Challenge",
    "Micro Machines",
    "Midnight Resistance",
    "Mig-29 Fighter Pilot",
    "Might and Magic - Gates to Another World",
    "Mighty Morphin Power Rangers - The Movie",
    "Mighty Morphin Power Rangers",
    "Mike Ditka Power Football",
    "Minnesota Fats - Pool Legend",
    "Miracle Piano Teaching System",
    "Monopoly",
    "Mortal Kombat 3",
    "Mortal Kombat II",
    "Mortal Kombat",
    "Ms. Pac-Man",
    "Muhammad Ali Heavyweight Boxing",
    "Mutant League Football",
    "Mutant League Hockey",
    "Mystic Defender",
    "Mystical Fighter",
    "NBA Action '94",
    "NBA Action '95 Starring David Robinson",
    "NBA All-Star Challenge",
    "NBA Hang Time",
    "NBA Jam - Tournament Edition",
    "NBA Jam",
    "NBA Live 95",
    "NBA Live 96",
    "NBA Live 97",
    "NBA Live 98",
    "NBA Showdown '94",
    "NCAA Final Four Basketball",
    "NCAA Football",
    "NFL '95",
    "NFL 98",
    "NFL Football '94 Starring Joe Montana",
    "NFL Quarterback Club 96",
    "NFL Quarterback Club",
    "NFL Sports Talk Football '93 Starring Joe Montana",
    "NHL '94",
    "NHL 95",
    "NHL 96",
    "NHL 97",
    "NHL 98",
    "NHL All-Star Hockey 95",
    "NHL Hockey",
    "NHLPA Hockey 93",
    "New Horizons",
    "Newman Haas IndyCar featuring Nigel Mansell",
    "Nigel Mansell's World Championship Racing",
    "No Escape",
    "Nobunaga's Ambition",
    "Normy's Beach Babe-O-Rama",
    "Oh Mummy Genesis",
    "Olympic Gold",
    "Olympic Summer Games",
    "Onslaught",
    "Ooze",
    "Operation Europe - Path to Victory 1939-45",
    "Out of This World",
    "OutRun 2019",
    "OutRun",
    "OutRunners",
    "Outlander",
    "P.T.O. - Pacific Theater of Operations",
    "PGA European Tour",
    "PGA Tour 96",
    "PGA Tour Golf II",
    "PGA Tour Golf III",
    "Pac-Attack",
    "Pac-Man 2 - The New Adventures",
    "Pac-Mania",
    "Pagemaster",
    "Paperboy 2",
    "Paperboy",
    "Pat Riley Basketball",
    "Pebble Beach Golf Links",
    "Pele II - World Tournament Soccer",
    "Pele!",
    "Pete Sampras Tennis",
    "Phantasy Star II",
    "Phantasy Star III - Generations of Doom",
    "Phantasy Star IV (Sample)",
    "Phantasy Star IV",
    "Phantom 2040",
    "Phelios",
    "Pier Solar and the Great Architects (En,Fr,Es)",
    "Pink Goes to Hollywood",
    "Pinocchio",
    "Pirates of Dark Water",
    "Pirates! Gold",
    "Pit-Fighter",
    "Pitfall - The Mayan Adventure",
    "Pocahontas",
    "Populous",
    "Power Monger",
    "Powerball",
    "Predator 2",
    "Primal Rage",
    "Prime Time NFL Starring Deion Sanders",
    "Prince of Persia",
    "Pro Moves Soccer",
    "Pro Quarterback",
    "Puggsy",
    "Punisher",
    "QuackShot Starring Donald Duck ~ QuackShot - I Love Donald Duck - Guruzia Ou no Hihou",
    "Quad Challenge",
    "R.B.I. Baseball '93",
    "R.B.I. Baseball '94",
    "R.B.I. Baseball 3",
    "R.B.I. Baseball 4",
    "Race Drivin'",
    "Radical Rex",
    "Raiden Densetsu ~ Raiden Trad",
    "Rambo III",
    "Rampart",
    "Ranger X",
    "Rastan Saga II",
    "Red Zone",
    "Ren & Stimpy Show Presents - Stimpy's Invention",
    "Revenge of Shinobi",
    "Revolution X",
    "Richard Scarry's BusyTown",
    "Rings of Power",
    "Risk",
    "Risky Woods",
    "Ristar",
    "Road Rash 3",
    "Road Rash II",
    "Road Rash",
    "RoadBlasters",
    "RoboCop 3",
    "RoboCop versus The Terminator",
    "Rock n' Roll Racing",
    "Rocket Knight Adventures",
    "Roger Clemens' MVP Baseball",
    "Rolling Thunder 2",
    "Rolling Thunder 3",
    "Rolo to the Rescue",
    "Romance of the Three Kingdoms II",
    "Romance of the Three Kingdoms III - Dragon of Destiny",
    "Rugby World Cup 95",
    "Sagaia",
    "Saint Sword",
    "Samurai Shodown",
    "Saturday Night Slammasters",
    "Scooby-Doo Mystery",
    "SeaQuest DSV",
    "Sega Sound Tool",
    "Senjou no Ookami II ~ Mercs",
    "Sesame Street Counting Cafe",
    "Shadow Blasters",
    "Shadow Dancer - The Secret of Shinobi",
    "Shadow of the Beast II",
    "Shadow of the Beast",
    "Shadowrun",
    "Shanghai II - Dragon's Eye",
    "Shaq-Fu",
    "Shining Force II",
    "Shining Force",
    "Shining in the Darkness",
    "Shinobi III - Return of the Ninja Master",
    "Shove It! ...The Warehouse Game",
    "Side Pocket",
    "Simpsons - Bart Vs. The Space Mutants",
    "Simpsons - Bart's Nightmare",
    "Skeleton Krew",
    "Skitchin'",
    "Slaughter Sport - Copy",
    "Slaughter Sport",
    "Socket",
    "Sol-Deace",
    "Soldiers of Fortune",
    "Sonic & Knuckles + Sonic The Hedgehog 3",
    "Sonic & Knuckles + Sonic The Hedgehog",
    "Sonic & Knuckles + Sonic the Hedgehog 2",
    "Sonic & Knuckles",
    "Sonic 3D Blast - Director's Cut",
    "Sonic 3D Blast ~ Sonic 3D Flickies' Island",
    "Sonic Spinball",
    "Sonic the Hedgehog 2",
    "Sonic the Hedgehog 3",
    "Sonic the Hedgehog",
    "Sorcerer's Kingdom",
    "Space Harrier II",
    "Space Invaders '91",
    "Sparkster",
    "Speedball 2 - Brutal Deluxe",
    "Spider-Man . Venom - Maximum Carnage",
    "Spider-Man X-Men - Arcade's Revenge",
    "Spider-Man vs. The Kingpin",
    "Spider-Man",
    "Spiritual Warfare",
    "Splatterhouse 2",
    "Splatterhouse 3",
    "Sports Talk Baseball",
    "Spot Goes to Hollywood",
    "Star Control",
    "Star Odyssey",
    "Star Trek - Deep Space Nine - Crossroads of Time",
    "Star Trek - The Next Generation - Echoes from the Past",
    "Starflight",
    "Stargate",
    "Steel Empire",
    "Steel Talons",
    "Stormlord",
    "Street Fighter II' - Special Champion Edition",
    "Street Smart",
    "Streets of Rage 2",
    "Streets of Rage 3",
    "Strider",
    "Sub-Terrania",
    "Summer Challenge",
    "Sunset Riders",
    "Super Baseball 2020",
    "Super Battleship - The Classic Naval Combat Game",
    "Super Hang-On",
    "Super High Impact",
    "Super Hydlide",
    "Super Monaco GP",
    "Super Off Road",
    "Super Smash T.V.",
    "Super Street Fighter II",
    "Super Thunder Blade",
    "Super Volleyball",
    "Superman",
    "Sword of Sodan",
    "Sword of Vermilion",
    "Syd of Valis",
    "Sylvester and Tweety in Cagey Capers ~ Sylvester & Tweety in Cagey Capers",
    "Syndicate",
    "T2 - Terminator 2 - Judgment Day",
    "T2 - The Arcade Game",
    "TNN Bass Tournament of Champions",
    "TNN Outdoors Bass Tournament '96",
    "TaleSpin",
    "Target Earth",
    "Task Force Harrier EX",
    "Tatsujin ~ Truxton",
    "Taz in Escape from Mars",
    "Taz-Mania",
    "Team USA Basketball",
    "TechnoClash",
    "Technocop",
    "Tecmo Super Baseball",
    "Tecmo Super Bowl II - Special Edition",
    "Tecmo Super Bowl III - Final Edition",
    "Tecmo Super Bowl",
    "Tecmo Super Hockey",
    "Tecmo Super NBA Basketball",
    "Tecmo World Cup",
    "Teenage Mutant Ninja Turtles - The Hyperstone Heist",
    "Teenage Mutant Ninja Turtles - Tournament Fighters",
    "Terminator",
    "Test Drive II - The Duel",
    "Theme Park",
    "Thomas the Tank Engine & Friends",
    "Thunder Force II",
    "Thunder Force III",
    "Thunder Fox",
    "Tick",
    "Time Killers",
    "Tinhead (Ballistic) (April, 1994)",
    "Tinhead (Spectrum HoloByte) (October, 1995)",
    "Tiny Toon Adventures - Acme All-Stars (USA, Korea)",
    "Tiny Toon Adventures - Buster's Hidden Treasure",
    "Todd's Adventures in Slime World",
    "ToeJam & Earl in Panic on Funkotron",
    "ToeJam & Earl",
    "Toki - Going Ape Spit",
    "Tom Mason's Dinosaurs for Hire",
    "Tom and Jerry - Frantic Antics!",
    "Tommy Lasorda Baseball",
    "Tony La Russa Baseball",
    "Top Gear 2",
    "Toughman Contest",
    "Toxic Crusaders",
    "Toy Story (Sample)",
    "Toy Story",
    "Toys - Let the Toy Wars begin!",
    "Trampoline Terror!",
    "Traysia",
    "Triple Play - Gold Edition",
    "Triple Play 96 [b]",
    "Trouble Shooter",
    "Troy Aikman NFL Football",
    "True Lies",
    "Turrican",
    "Twin Cobra - Desert Attack Helicopter",
    "Two Crude Dudes",
    "Tyrants - Fight through Time",
    "Ultimate Mortal Kombat 3",
    "Ultimate Qix",
    "Ultracore_MD_World_Box",
    "Uncharted Waters",
    "Universal Soldier",
    "Unnecessary Roughness '95",
    "Urban Strike",
    "VR Troopers",
    "Valis III",
    "Valis",
    "Vapor Trail",
    "Vectorman 2 (Sample) (1996-08-28)",
    "Vectorman 2",
    "Vectorman",
    "Venom . Spider-Man - Separation Anxiety",
    "Viewpoint",
    "Virtua Fighter 2",
    "Virtua Racing",
    "Virtual Bart",
    "Virtual Pinball",
    "WWF Raw",
    "WWF Royal Rumble",
    "WWF Super WrestleMania",
    "WWF WrestleMania - The Arcade Game",
    "Wacky Worlds Creativity Studio",
    "Wardner",
    "Warlock",
    "WarpSpeed",
    "Warrior of Rome II",
    "Warrior of Rome",
    "Warsong",
    "Water Margin - The Tales of Clouds and Winds",
    "Wayne Gretzky and the NHLPA All-Stars",
    "Wayne's World",
    "Weaponlord",
    "Wheel of Fortune",
    "Where in Time Is Carmen Sandiego",
    "Where in the World Is Carmen Sandiego",
    "Whip Rush",
    "Williams Arcade's Greatest Hits",
    "Wimbledon Championship Tennis",
    "Wings of Wor",
    "Winter Olympic Games (En,Fr,De,Es,It,Pt,Sv,No)",
    "Wiz 'N' Liz",
    "Wolfchild",
    "Wolverine - Adamantium Rage",
    "Wonder Boy in Monster World",
    "World Championship Soccer II",
    "World Class Leaderboard Golf",
    "World Cup Soccer ~ World Championship Soccer",
    "World Cup USA 94",
    "World Heroes",
    "World Series Baseball '95",
    "World Series Baseball '96",
    "World Series Baseball 98",
    "World Series Baseball",
    "World Trophy Soccer",
    "World of Illusion Starring Mickey Mouse and Donald Duck (USA, Korea)",
    "X-Men 2 - Clone Wars",
    "X-Men",
    "X-Perts",
    "Ys III",
    "Zany Golf (Unl)",
    "Zany Golf",
    "Zero Tolerance",
    "Zero the Kamikaze Squirrel",
    "Zombies Ate My Neighbors",
    "Zool - Ninja of the 'Nth' Dimension",
    "Zoom!",
    "Zoop",
    "tetris-gen"
]

export const sgGenEUTitles = [
    "688 Attack Sub",
    "AAAHH!!! Real Monsters",
    "ATP Tour",
    "Action Replay",
    "Addams Family Values",
    "Addams Family",
    "Adventures of Batman & Robin",
    "Adventures of Mighty Max",
    "Aero the Acro-Bat 2",
    "Aero the Acro-Bat",
    "After Burner II",
    "Al Michaels Announces HardBall III",
    "Aladdin",
    "Alex Kidd in the Enchanted Castle",
    "Alien 3",
    "Alien Soldier",
    "Alien Storm",
    "Alisia Dragoon",
    "Altered Beast",
    "Andre Agassi Tennis",
    "Animaniacs",
    "Another World",
    "Aquatic Games Starring James Pond and the Aquabats",
    "Arcade Classics",
    "Arcade Legends Sega Mega Drive ~ Arcade Legends Sega Genesis ~ Mega Drive Play TV",
    "Arcade Legends Street Fighter II' - Special Champion Edition ~ Mega Drive Play TV 3",
    "Arch Rivals - The Arcade Game",
    "Ariel the Little Mermaid",
    "Arnold Palmer Tournament Golf",
    "Arrow Flash",
    "Art Alive",
    "Art of Fighting",
    "Asterix and the Great Rescue",
    "Asterix and the Power of the Gods",
    "Atomic Runner",
    "Australian Rugby League",
    "Ayrton Senna's Super Monaco GP II",
    "Back to the Future Part III",
    "Ball Jacks",
    "Ballz 3D - Fighting at Its Ballziest ~ Ballz 3D - The Battle of the Ballz",
    "Bare Knuckle - Ikari no Tekken ~ Streets of Rage",
    "Bare Knuckle II - Shitou e no Requiem ~ Streets of Rage II",
    "Barkley Shut Up and Jam!",
    "Batman Forever",
    "Batman Returns",
    "Batman",
    "Battle Squadron",
    "Battletoads",
    "Beavis and Butt-Head",
    "Beggar Prince",
    "Bill Walsh College Football",
    "Bio Hazard Battle",
    "Blades of Vengeance",
    "Blockout",
    "Bloodshot",
    "Body Count",
    "Bonanza Bros.",
    "Bonkers",
    "Boogerman - A Pick and Flick Adventure",
    "Bram Stoker's Dracula",
    "Brian Lara Cricket 96",
    "Brian Lara Cricket",
    "Brutal - Paws of Fury",
    "Bubba 'N' Stix",
    "Bubble and Squeak",
    "Bubsy II",
    "Bubsy in - Claws Encounters of the Furred Kind",
    "Buck Rogers - Countdown to Doomsday",
    "Budokan - The Martial Spirit",
    "Bugs Bunny in Double Trouble",
    "Bulls versus Blazers and the NBA Playoffs",
    "Bulls vs Lakers and the NBA Playoffs",
    "Burning Force",
    "California Games",
    "Cannon Fodder",
    "Captain America and the Avengers",
    "Captain Planet and the Planeteers",
    "Cascade",
    "Castle of Illusion Starring Mickey Mouse",
    "Castlevania - The New Generation",
    "Centurion - Defender of Rome",
    "Chakan",
    "Champions World Class Soccer",
    "Chaos Engine",
    "Cheese Cat-Astrophe Starring Speedy Gonzales",
    "Chiki Chiki Boys",
    "Chuck Rock II - Son of Chuck",
    "Chuck Rock",
    "Classic Collection",
    "ClayFighter",
    "Cliffhanger",
    "Columns",
    "Combat Cars",
    "Comix Zone",
    "Cool Spot",
    "Corporation",
    "Cosmic Spacehead",
    "Crack Down",
    "Crue Ball - Heavy Metal Pinball",
    "CutThroat Island",
    "Cyberball",
    "Cyborg Justice",
    "DEcapAttack",
    "DJ Boy",
    "Daffy Duck in Hollywood",
    "Daisenpuu ~ Twin Hawk",
    "Dark Castle",
    "David Robinson's Supreme Court",
    "Davis Cup Tennis ~ Davis Cup World Tour",
    "Death and Return of Superman",
    "Demolition Man",
    "Desert Demolition Starring Road Runner and Wile E. Coyote",
    "Desert Strike - Return to the Gulf",
    "Dick Tracy",
    "Dino Dini's Soccer",
    "Disney Collection - QuackShot Starring Donald Duck + Castle of Illusion Starring Mickey Mouse",
    "Double Clutch",
    "Double Dragon 3 - The Arcade Game",
    "Double Dragon",
    "Dr. Robotnik's Mean Bean Machine",
    "Dragon - The Bruce Lee Story",
    "Dragon's Fury",
    "Dragon's Revenge",
    "Dune II - The Battle for Arrakis",
    "Dungeons & Dragons - Warriors of the Eternal Sun",
    "Dynamite Duke",
    "Dynamite Headdy",
    "EA Hockey",
    "EA Sports Double Header",
    "Earthworm Jim 2",
    "Earthworm Jim",
    "Ecco - The Tides of Time",
    "Ecco the Dolphin",
    "Empire of Steel",
    "Eternal Champions",
    "European Club Soccer",
    "Evander Holyfield's 'Real Deal' Boxing",
    "Ex-Mutants",
    "Exo Squad",
    "F-117 Night Storm",
    "F-15 Strike Eagle II",
    "F-22 Interceptor - Advanced Tactical Fighter",
    "F1 - World Championship Edition",
    "F1",
    "FIFA 98 - Road to World Cup",
    "FIFA International Soccer",
    "FIFA Soccer 95",
    "FIFA Soccer 96",
    "FIFA Soccer 97",
    "Faery Tale Adventure",
    "Fantasia",
    "Fantastic Dizzy",
    "Fatal Fury 2",
    "Fatal Fury",
    "Fatal Labyrinth",
    "Fatal Rewind",
    "Ferrari Grand Prix Challenge",
    "Fever Pitch Soccer",
    "Fire Shark",
    "Flashback",
    "Flicky",
    "Flink",
    "Flintstones",
    "Flux",
    "Foreman for Real",
    "Forgotten Worlds",
    "Frank Thomas Big Hurt Baseball",
    "Fun 'n Games",
    "G-LOC - Air Battle",
    "Gain Ground",
    "Game Genie",
    "Garfield - Caught in the Act",
    "Gauntlet IV",
    "General Chaos",
    "Generations Lost",
    "George Foreman's KO Boxing",
    "Ghostbusters",
    "Global Gladiators",
    "Gods",
    "Golden Axe II",
    "Golden Axe",
    "GrandSlam - The Tennis Tournament",
    "Greatest Heavyweights",
    "Greendog - The Beached Surfer Dude!",
    "Gunship",
    "Gunstar Heroes",
    "Gynoug",
    "Hard Drivin'",
    "HardBall '94",
    "HardBall!",
    "Haunting Starring Polterguy",
    "Havoc",
    "Hellfire",
    "Herzog Zwei",
    "Home Alone",
    "Hook",
    "Hurricanes",
    "Hyper Dunk",
    "IMG International Tour Tennis",
    "Immortal",
    "Incredible Crash Dummies",
    "Incredible Hulk",
    "Indiana Jones and the Last Crusade",
    "International Rugby",
    "International Sensible Soccer",
    "International Superstar Soccer Deluxe",
    "Izzy's Quest for the Olympic Rings",
    "Jack Nicklaus' Power Challenge Golf",
    "James 'Buster' Douglas Knockout Boxing",
    "James Bond 007 - The Duel",
    "James Pond - Underwater Agent",
    "James Pond 3",
    "James Pond II - Codename - Robocod",
    "Jewel Master",
    "Jimmy White's Whirlwind Snooker",
    "Joe Montana Football",
    "Joe Montana II Sports Talk Football",
    "John Madden Football '92",
    "John Madden Football '93",
    "John Madden Football",
    "Jordan vs Bird",
    "Judge Dredd",
    "Jungle Book",
    "Jungle Strike",
    "Jurassic Park - Rampage Edition",
    "Jurassic Park",
    "Justice League Task Force",
    "Kawasaki Superbike Challenge",
    "Kick Off 3 - European Challenge",
    "Kid Chameleon",
    "King of the Monsters",
    "King's Bounty - The Conqueror's Quest",
    "Klax (Tengen)",
    "Krusty's Super Fun House",
    "LHX Attack Chopper",
    "Lakers versus Celtics and the NBA Playoffs",
    "Landstalker - The Treasures of King Nole",
    "Last Action Hero",
    "Last Battle",
    "Lawnmower Man",
    "Legend of Galahad ~ Galahad",
    "Legend of Wukong",
    "Lemmings 2 - The Tribes",
    "Lemmings",
    "Lethal Enforcers II - Gun Fighters",
    "Lethal Enforcers",
    "Light Crusader",
    "Lion King",
    "Lost Vikings",
    "Lost World - Jurassic Park",
    "Lotus II",
    "Lotus Turbo Challenge",
    "M-1 Abrams Battle Tank",
    "Madden NFL '94",
    "Madden NFL 95",
    "Madden NFL 96",
    "Madden NFL 97",
    "Magic Girl featuring Ling Ling the Little Witch",
    "Man Overboard!",
    "Marble Madness",
    "Mario Andretti Racing",
    "Mario Lemieux Hockey",
    "Marko's Magic Football",
    "Marsupilami",
    "Mazin Wars",
    "McDonald's Treasure Land Adventure",
    "Mega 6 Vol. 3",
    "Mega Bomberman",
    "Mega Games 2",
    "Mega Games 6 Vol. 2",
    "Mega Games 6",
    "Mega Games I",
    "Mega Man - The Wily Wars",
    "Mega SWIV",
    "Mega Turrican",
    "Mega-Lo-Mania",
    "Menacer 6-Game Cartridge",
    "Michael Jackson's Moonwalker",
    "Mickey Mania",
    "Micro Machines 2 - Turbo Tournament",
    "Micro Machines Military",
    "Micro Machines Turbo Tournament 96",
    "Micro Machines",
    "Midway Presents Arcade's Greatest Hits",
    "Mig-29 Fighter Pilot",
    "Might and Magic - Gates to Another World",
    "Mighty Morphin Power Rangers - The Movie",
    "Mighty Morphin Power Rangers",
    "Mike Ditka Power Football",
    "Mortal Kombat 3",
    "Mortal Kombat II Unlimited",
    "Mortal Kombat II",
    "Mortal Kombat",
    "Mr. Nutz",
    "Ms. Pac-Man",
    "Muhammad Ali Heavyweight Boxing",
    "Mutant League Football",
    "Mutant League Hockey",
    "Mystic Defender",
    "NBA Action '95 Starring David Robinson",
    "NBA All-Star Challenge",
    "NBA Hang Time",
    "NBA Jam - Tournament Edition",
    "NBA Jam",
    "NBA Live 95",
    "NBA Live 96",
    "NBA Live 97",
    "NBA Showdown '94",
    "NFL Quarterback Club 96",
    "NFL Quarterback Club",
    "NFL Sports Talk Football '93 Starring Joe Montana",
    "NHL '94",
    "NHL 95",
    "NHL 96",
    "NHL 97",
    "NHLPA Hockey 93",
    "Newman Haas IndyCar featuring Nigel Mansell",
    "Nigel Mansell's World Championship Racing",
    "Normy's Beach Babe-O-Rama",
    "Oh Mummy Genesis",
    "Olympic Gold",
    "Olympic Summer Games",
    "Onslaught",
    "Ooze",
    "Ottifants",
    "OutRun 2019",
    "OutRun",
    "PGA European Tour",
    "PGA Tour 96",
    "PGA Tour Golf II",
    "PGA Tour Golf III",
    "Pac-Mania",
    "Pac-Panic",
    "Pagemaster",
    "Paperboy 2",
    "Paperboy",
    "Pebble Beach Golf Links",
    "Pele II - World Tournament Soccer",
    "Pele!",
    "Pete Sampras Tennis",
    "Phantasy Star II",
    "Phantasy Star III - Generations of Doom",
    "Phantasy Star IV",
    "Phantom 2040",
    "Phelios",
    "Pier Solar and the Great Architects (En,Fr,Es)",
    "Pink Goes to Hollywood",
    "Pinocchio",
    "Pirates of Dark Water",
    "Pit-Fighter",
    "Pitfall - The Mayan Adventure",
    "Pocahontas",
    "Populous",
    "Power Drive",
    "Power Monger",
    "Predator 2",
    "Premier Manager 97",
    "Premier Manager",
    "Primal Rage",
    "Prince of Persia",
    "Pro Action Replay 2",
    "Pro Action Replay",
    "Probotector",
    "Psycho Pinball",
    "Puggsy",
    "Punisher",
    "QuackShot Starring Donald Duck ~ QuackShot - I Love Donald Duck - Guruzia Ou no Hihou",
    "R.B.I. Baseball '94",
    "Radical Rex",
    "Rambo III",
    "Ranger X",
    "Red Zone",
    "Ren & Stimpy Show Presents - Stimpy's Invention",
    "Revenge of Shinobi",
    "Revolution X",
    "Rings of Power",
    "Rise of the Robots",
    "Risky Woods",
    "Ristar",
    "Road Rash 3",
    "Road Rash II",
    "Road Rash",
    "RoboCop 3",
    "RoboCop versus The Terminator",
    "Rock 'n' Roll Racing",
    "Rocket Knight Adventures",
    "Rolling Thunder 2",
    "Rolo to the Rescue",
    "Rugby World Cup 95",
    "Sampras Tennis 96",
    "Samurai Shodown",
    "Saturday Night Slammasters",
    "SeaQuest DSV",
    "Second Samurai",
    "Sega Sports 1",
    "Senjou no Ookami II ~ Mercs",
    "Sensible Soccer",
    "Shadow Dancer - The Secret of Shinobi",
    "Shadow of the Beast II",
    "Shadow of the Beast",
    "Shaq-Fu",
    "Shining Force II",
    "Shining Force",
    "Shining in the Darkness",
    "Shinobi III - Return of the Ninja Master",
    "Side Pocket",
    "Simpsons - Bart vs. the Space Mutants",
    "Simpsons - Bart's Nightmare",
    "Skeleton Krew",
    "Skitchin'",
    "Smurfs Travel the World",
    "Smurfs",
    "Snake Rattle n Roll",
    "Soleil",
    "Sonic & Knuckles + Sonic The Hedgehog 2",
    "Sonic & Knuckles + Sonic The Hedgehog 3",
    "Sonic & Knuckles",
    "Sonic 3",
    "Sonic 3D Blast - Director's Cut",
    "Sonic 3D Blast ~ Sonic 3D Flickies' Island",
    "Sonic Compilation",
    "Sonic Spinball",
    "Sonic The Hedgehog 2",
    "Sonic The Hedgehog",
    "Space Harrier II",
    "Sparkster",
    "Speedball 2",
    "Spider-Man . Venom - Maximum Carnage",
    "Spider-Man X-Men - Arcade's Revenge",
    "Spider-Man vs. The Kingpin",
    "Spider-Man",
    "Spirou",
    "Splatterhouse 2",
    "Spot Goes to Hollywood",
    "Star Control",
    "Star Odyssey",
    "Star Trek - Deep Space Nine - Crossroads of Time",
    "Starflight",
    "Stargate",
    "Steel Talons",
    "Story of Thor",
    "Street Fighter II' - Special Champion Edition",
    "Street Racer",
    "Streets of Rage 3",
    "Strider II",
    "Strider",
    "Striker",
    "Sub-Terrania",
    "Summer Challenge",
    "Sunset Riders",
    "Super Baseball 2020",
    "Super Fantasy Zone",
    "Super Hang-On",
    "Super Hydlide",
    "Super Kick Off",
    "Super League",
    "Super Off Road",
    "Super Real Basketball",
    "Super Skidmarks",
    "Super Smash T.V.",
    "Super Street Fighter II",
    "Super Thunder Blade",
    "Superman - The Man of Steel",
    "Sword of Sodan",
    "Sword of Vermilion",
    "Sylvester and Tweety in Cagey Capers ~ Sylvester & Tweety in Cagey Capers",
    "Syndicate",
    "T2 - Terminator 2 - Judgment Day",
    "T2 - The Arcade Game",
    "TaleSpin",
    "Talmit's Adventure",
    "Tatsujin ~ Truxton",
    "Taz in Escape from Mars",
    "Taz-Mania",
    "Team USA Basketball",
    "TechnoClash",
    "Teenage Mutant Hero Turtles - The Hyperstone Heist",
    "Teenage Mutant Hero Turtles - Tournament Fighters",
    "Terminator",
    "Test Drive II - The Duel",
    "Theme Park",
    "Thunder Force II",
    "Thunder Force III",
    "Thunder Force IV",
    "Time Killers",
    "Tintin in Tibet",
    "Tiny Toon Adventures - Acme All-Stars",
    "Tiny Toon Adventures - Buster's Hidden Treasure",
    "ToeJam & Earl in Panic on Funkotron",
    "ToeJam & Earl",
    "Toki - Going Ape Spit",
    "Total Football",
    "Toughman Contest",
    "Toy Story",
    "True Lies",
    "Turbo OutRun",
    "Turrican",
    "Two Crude Dudes",
    "Two Tribes - Populous II",
    "Ultimate Mortal Kombat 3",
    "Ultimate Soccer",
    "Universal Soldier",
    "Urban Strike",
    "VR Troopers",
    "Vectorman",
    "Venom . Spider-Man - Separation Anxiety",
    "Virtua Fighter 2",
    "Virtua Racing",
    "Virtual Bart",
    "Virtual Pinball",
    "WWF Raw",
    "WWF Royal Rumble",
    "WWF Super WrestleMania",
    "WWF WrestleMania - The Arcade Game",
    "Warlock",
    "WarpSpeed",
    "Wayne Gretzky and the NHLPA All-Stars",
    "Where in Time Is Carmen Sandiego",
    "Where in the World Is Carmen Sandiego",
    "Wimbledon",
    "Winter Olympics",
    "Wiz 'n' Liz - The Frantic Wabbit Wescue",
    "Wolverine - Adamantium Rage",
    "Wonder Boy III - Monster Lair",
    "Wonder Boy in Monster World",
    "World Championship Soccer II",
    "World Class Leader Board",
    "World Cup Italia '90",
    "World Cup USA 94",
    "World of Illusion Starring Mickey Mouse and Donald Duck",
    "Worms",
    "Wrestle War",
    "X-Men 2 - Clone Wars",
    "X-Men",
    "Xenon 2 - Megablast",
    "Yogi Bear - Cartoon Capers",
    "Zany Golf",
    "Zero Tolerance",
    "Zero Wing",
    "Zero the Kamikaze Squirrel",
    "Zombies",
    "Zool - Ninja of the 'Nth' Dimension",
    "Zoom!",
    "Zoop"
]

export const sgGenJPNTitles = [
    "007 Shitou - The Duel",
    "16t",
    "2020 Nen Super Baseball",
    "A Ressha de Ikou MD",
    "Aa Harimanada",
    "Advanced Busterhawk Gleylancer",
    "Aero Blasters",
    "After Burner II",
    "Air Diver",
    "Air Management - Oozora ni Kakeru",
    "Air Management II - Koukuuou o Mezase",
    "Aladdin",
    "Alex Kidd - Tenkuu Majou",
    "Alien Soldier",
    "Alien Storm",
    "Alisia Dragoon",
    "Aoki Ookami to Shiroki Mejika - Genchou Hishi",
    "Arcade Legends Sega Mega Drive ~ Arcade Legends Sega Genesis ~ Mega Drive Play TV",
    "Arcade Legends Street Fighter II' - Special Champion Edition ~ Mega Drive Play TV 3",
    "Arcus Odyssey",
    "Arrow Flash",
    "Art Alive",
    "Atomic Robo-Kid",
    "Awesome Possum... ...Kicks Dr. Machino's Butt",
    "Aworg",
    "Ayrton Senna's Super Monaco GP II",
    "Bad Omen",
    "Bahamut Senki",
    "Ball Jacks",
    "Bare Knuckle - Ikari no Tekken ~ Streets of Rage",
    "Bare Knuckle II - Shitou e no Requiem ~ Streets of Rage II",
    "Bare Knuckle III",
    "Batman Forever",
    "Batman Returns",
    "Batman",
    "Battle Golfer Yui",
    "Battle Mania Daiginjou",
    "Battle Mania",
    "Battletoads",
    "Beast Warriors",
    "Beggar Prince",
    "Bishoujo Senshi Sailor Moon",
    "Blockout",
    "Blue Almanac",
    "Bonanza Bros.",
    "Boogie Woogie Bowling",
    "Burning Force",
    "Caesar no Yabou II",
    "Caesar no Yabou",
    "Captain Lang",
    "Cascade",
    "Chameleon Kid",
    "Champions World Class Soccer",
    "Chelnov",
    "Chibi Maruko-chan - Wakuwaku Shopping",
    "Chiki Chiki Boys",
    "Chou Kyuukai Miracle Nine",
    "Chou Touryuu Retsuden - Dino Land",
    "Chuck Rock II",
    "Columns III - Taiketsu! Columns World",
    "Columns",
    "Comix Zone",
    "Contra - The Hard Corps",
    "Cool Spot",
    "Crack Down",
    "Crayon Shin-chan - Arashi o Yobu Enji",
    "Crude Buster",
    "Crue Ball",
    "Crying - Aseimei Sensou",
    "Curse",
    "Cutie Suzuki no Ringside Angel",
    "Cyber Police - ESWAT",
    "Cyberball",
    "DJ Boy",
    "Dahna - Megami Tanjou",
    "Daikoukai Jidai II",
    "Daikoukai Jidai",
    "Daimakaimura",
    "Daisenpuu ~ Twin Hawk",
    "Dangerous Seed",
    "Darius II",
    "Darwin 4081",
    "David Robinson Basketball",
    "Davis Cup Tennis",
    "Desert Strike - Wangan Sakusen ~ Desert Strike",
    "Devil Crash MD",
    "Dial Q o Mawase!",
    "Dick Tracy",
    "Divine Sealing",
    "Doraemon - Yume Dorobou to 7 Nin no Gozans",
    "Double Dragon II - The Revenge",
    "Dragon Ball Z - Buyuu Retsuden",
    "Dragon Slayer - Eiyuu Densetsu II",
    "Dragon Slayer - Eiyuu Densetsu",
    "Dragon's Eye Plus - Shanghai III",
    "Dragon's Revenge",
    "Dream Team USA",
    "Dyna Brothers 2",
    "Dyna Brothers",
    "Dynamite Duke",
    "Dynamite Headdy",
    "EA Hockey",
    "Ecco the Dolphin II",
    "Ecco the Dolphin",
    "El.Viento",
    "Elemental Master",
    "Eliminate Down",
    "Eternal Champions",
    "Europa Sensen",
    "Evander Holyfield's 'Real Deal' Boxing",
    "Ex-Ranza",
    "Exile - Toki no Hazama he",
    "F-117 Stealth - Operation - Night Storm",
    "F-22 Interceptor - Advanced Tactical Fighter",
    "F1 Circus MD",
    "FIFA International Soccer",
    "FZ Senki Axis ~ Final Zone",
    "Fantasia",
    "Fastest 1",
    "Fatman",
    "Fighting Masters",
    "Final Blow",
    "Fire Mustang",
    "Flashback",
    "Flintstones",
    "Foreman for Real",
    "Forgotten Worlds",
    "From TV Animation Slam Dunk - Kyougou Makkou Taiketsu!",
    "Fushigi no Umi no Nadia",
    "G-LOC - Air Battle",
    "Gaiares",
    "Gain Ground",
    "Galaxy Force II",
    "Gambler Jiko Chuushinha - Katayama Masayuki no Mahjong Doujou",
    "Garou Densetsu - Shukumei no Tatakai",
    "Garou Densetsu 2 - Aratanaru Tatakai",
    "Gauntlet",
    "General Chaos Daikonsen",
    "Ghostbusters",
    "Go Net",
    "Gods",
    "Golden Axe II",
    "Golden Axe III",
    "Golden Axe",
    "Gouketsuji Ichizoku",
    "Granada",
    "GrandSlam - The Tennis Tournament '92",
    "Great Circus Mystery - Mickey to Minnie Magical Adventure 2",
    "Greatest Heavyweights",
    "Gunstar Heroes (Sample) (April, 1993)",
    "Gunstar Heroes",
    "Gynoug",
    "Hard Drivin'",
    "Heavy Unit - Mega Drive Special",
    "Hellfire",
    "Herzog Zwei",
    "Hokuto no Ken - Shin Seikimatsu Kyuuseishu Densetsu",
    "Honoo no Toukyuuji - Dodge Danpei",
    "Hybrid Front",
    "Hyokkori Hyoutan-jima - Daitouryou wo Mezase!",
    "Hyper Dunk - The Playoff Edition",
    "Hyper Marbles",
    "I Love Mickey Mouse - Fushigi no Oshiro Daibouken",
    "I Love Mickey and Donald - Fushigi na Magic Box",
    "Ikasuze! Koi no Doki Doki Penguin Land MD",
    "Insector X",
    "J. League Champion Soccer",
    "J. League Pro Striker 2",
    "J. League Pro Striker Perfect",
    "J. League Pro Striker",
    "James Pond II",
    "Janou Touryuumon",
    "Jantei Monogatari",
    "Jashin Draxos",
    "Jewel Master",
    "Joe Montana Football",
    "Joe Montana II Sports Talk Football",
    "John Madden Football - Pro Football",
    "Jordan vs Bird - One on One",
    "JuJu Densetsu",
    "Judge Dredd",
    "Junction",
    "Jungle Strike - Uketsugareta Kyouki",
    "Jurassic Park",
    "Justice League Task Force",
    "Juuouki",
    "Juusou Kihei Leynos",
    "Ka-Ge-Ki",
    "Kick Boxing",
    "Kidou Keisatsu Patlabor - 98-Shiki Kidou Seyo!",
    "Killing Game Show",
    "King Salmon",
    "King of the Monsters",
    "Kishi Densetsu",
    "Kiss Shot",
    "Klax (Namco)",
    "Koutetsu Teikoku",
    "Kujaku Ou 2 - Geneijou",
    "Kuuga - Operation Code 'Vapor Trail'",
    "Kyuukai Douchuuki",
    "Kyuukyoku Tiger",
    "LHX Attack Chopper",
    "Landstalker - Koutei no Zaihou",
    "Langrisser II",
    "Langrisser",
    "Legend of Wukong",
    "Lemmings",
    "Lethal Enforcers",
    "Light Crusader",
    "Lion King",
    "Lord Monarch - Tokoton Sentou Densetsu",
    "Madou Monogatari I",
    "Magic Girl featuring Ling Ling the Little Witch",
    "Magical Hat no Buttobi Turbo! Daibouken",
    "Magical Taruruuto-kun",
    "Mahjong Cop Ryuu - Shiro Ookami no Yabou",
    "Mamono Hunter Youko - Dai 7 no Keishou",
    "Maou Renjishi",
    "Marble Madness",
    "Marvel Land",
    "Master of Monsters",
    "Master of Weapon",
    "Maten no Soumetsu",
    "Mazin Saga",
    "McDonald's Treasure Land Adventure",
    "Medal City",
    "Mega Anser",
    "Mega Lo Mania",
    "MegaMind",
    "MegaPanel",
    "MegaTrax",
    "Metal Fangs",
    "Michael Jackson's Moonwalker",
    "Mickey Mania - The Timeless Adventures of Mickey Mouse",
    "Midnight Resistance",
    "Mig-29 Fighter Pilot",
    "Minato no Traysia",
    "Monster World IV",
    "Mortal Kombat II",
    "Mortal Kombat",
    "Mugen Senshi Valis",
    "Musha Aleste - Full Metal Fighter Ellinor",
    "Mutant League Football",
    "NBA Jam - Tournament Edition",
    "NBA Jam",
    "NBA Playoffs - Bulls vs Blazers",
    "NBA Pro Basketball '94",
    "NBA Pro Basketball - Bulls vs Lakers and the NBA Playoffs",
    "NFL Football '94",
    "NFL Pro Football '94",
    "NFL Quarterback Club",
    "NHK Taiga Drama - Taiheiki",
    "Nakajima Satoru Kanshuu - F-1 Grand Prix",
    "Nakajima Satoru Kanshuu - F-1 Hero MD",
    "Nakajima Satoru Kanshuu - F-1 Super License",
    "Nekketsu Koukou Dodgeball-bu - Soccer Hen MD",
    "New 3D Golf Simulation - Devil's Course",
    "New 3D Golf Simulation - Harukanaru Augusta",
    "New 3D Golf Simulation - Pebble Beach no Hatou",
    "New 3D Golf Simulation - Waialae no Kiseki",
    "NewZealand Story",
    "Newman Haas IndyCar featuring Nigel Mansell",
    "Nikkan Sports Pro Yakyuu Van",
    "Ninja Burai Densetsu",
    "Nobunaga no Yabou - Bushou Fuuunroku",
    "Nobunaga no Yabou - Haouden",
    "Nobunaga no Yabou - Zenkoku Ban",
    "Oh Mummy Genesis",
    "Olympic Gold",
    "Ooze",
    "Osomatsu-kun Hachamecha Gekijou",
    "OutRun 2019",
    "OutRun",
    "OutRunners",
    "Ozaki Naomichi no Super Masters",
    "PGA Tour Golf II",
    "Pachinko Kuunyan",
    "Paddle Fighter",
    "Panorama Cotton",
    "Paperboy",
    "Party Quiz Mega Q",
    "Pepenga Pengo",
    "Phantasy Star - Sennenki no Owari ni",
    "Phantasy Star Fukkokuban",
    "Phantasy Star II - Amia's Adventure",
    "Phantasy Star II - Anne's Adventure",
    "Phantasy Star II - Huey's Adventure",
    "Phantasy Star II - Kaerazaru Toki no Owari ni",
    "Phantasy Star II - Kinds's Adventure",
    "Phantasy Star II - Nei's Adventure",
    "Phantasy Star II - Rudger's Adventure",
    "Phantasy Star II - Shilka's Adventure",
    "Phantasy Star II - Yushis's Adventure",
    "Phelios",
    "Pier Solar and the Great Architects (En,Fr,Es)",
    "Pit-Fighter",
    "Populous",
    "Power Athlete",
    "Power Monger",
    "Pro Striker Final Stage",
    "Pro Yakyuu Super League '91",
    "Psy-O-Blade",
    "Pulseman",
    "Putter Golf",
    "Puyo Puyo Tsuu",
    "Puyo Puyo",
    "Puzzle & Action - Ichidanto-R",
    "Puzzle & Action - Tanto-R",
    "Pyramid Magic II",
    "Pyramid Magic III",
    "Pyramid Magic Special",
    "Pyramid Magic",
    "QuackShot Starring Donald Duck ~ QuackShot - I Love Donald Duck - Guruzia Ou no Hihou",
    "R.B.I. Baseball 4",
    "Raiden Densetsu ~ Raiden Trad",
    "Rainbow Islands Extra",
    "Rambo III",
    "Rampart",
    "Ransei no Hasha",
    "Rastan Saga II",
    "Rent a Hero",
    "Riddle Wired",
    "Ristar - The Shooting Star",
    "Road Rash II",
    "Road Rash",
    "RoadBlasters",
    "RoboCop versus The Terminator",
    "Robot Battler",
    "Rocket Knight Adventures",
    "Rockman - Mega World",
    "Rolling Thunder 2",
    "Royal Blood",
    "Runark",
    "Ryuuko no Ken",
    "SD Valis",
    "Saint Sword",
    "Same! Same! Same!",
    "Samurai Spirits",
    "Sangokushi II",
    "Sangokushi III",
    "Sangokushi Retsuden - Ransei no Eiyuutachi",
    "Sansan",
    "Sega Art Tool",
    "Senjou no Ookami II ~ Mercs",
    "Shadow Dancer - The Secret of Shinobi",
    "Shadow of the Beast - Mashou no Okite",
    "Shi no Meikyuu - Labyrinth of Death",
    "Shijou Saidai no Soukoban",
    "Shikinjou",
    "Shin Souseiki Ragnacenty",
    "Shining Force - Kamigami no Isan",
    "Shining Force II - Inishie no Fuuin",
    "Shining and the Darkness",
    "Shiten Myouou",
    "Shougi no Hoshi",
    "Shura no Mon",
    "Side Pocket",
    "Slap Fight MD",
    "Slime World",
    "Snow Bros. - Nick & Tom",
    "Sonic & Knuckles + Sonic The Hedgehog 2",
    "Sonic & Knuckles + Sonic The Hedgehog 3",
    "Sonic & Knuckles + Sonic The Hedgehog",
    "Sonic & Knuckles",
    "Sonic 3D Blast - Director's Cut",
    "Sonic Eraser",
    "Sonic Spinball",
    "Sonic The Hedgehog 2",
    "Sonic The Hedgehog 3",
    "Sonic The Hedgehog",
    "Sorcer Kingdom",
    "Sorcerian",
    "Space Funky B.O.B.",
    "Space Harrier II (Launch Cart)",
    "Space Harrier II",
    "Space Invaders 90",
    "Sparkster - Rocket Knight Adventures 2",
    "Speedball 2",
    "Spider-Man . Venom - Maximum Carnage",
    "Spider-Man vs. The Kingpin",
    "Splatterhouse Part 2",
    "Splatterhouse Part 3",
    "Star Cruiser",
    "Star Odyssey",
    "Steel Talons",
    "Stormlord",
    "Story of Thor - Hikari o Tsugumono",
    "Street Fighter II' Plus - Champion Edition (Japan, Asia, Korea)",
    "Street Smart",
    "Strider Hiryuu",
    "Super Airwolf",
    "Super Daisenryaku",
    "Super Fantasy Zone",
    "Super H.Q.",
    "Super Hang-On",
    "Super Hydlide",
    "Super League",
    "Super Monaco GP",
    "Super Real Basketball",
    "Super Shinobi II",
    "Super Shinobi",
    "Super Street Fighter II - The New Challengers",
    "Super Thunder Blade (Launch Cart)",
    "Super Thunder Blade",
    "Super Volley Ball",
    "Surging Aura",
    "Sword of Sodan",
    "T2 - The Arcade Game",
    "Taikou Risshiden",
    "Task Force Harrier EX",
    "Tatsujin ~ Truxton",
    "Taz-Mania",
    "Tecmo Super Bowl II - Special Edition",
    "Tecmo Super Bowl",
    "Tecmo Super NBA Basketball",
    "Tecmo World Cup '92",
    "Teddy Boy Blues",
    "Teenage Mutant Ninja Turtles - Return of the Shredder",
    "Teenage Mutant Ninja Turtles - Tournament Fighters",
    "Teitoku no Ketsudan",
    "Tel-Tel Mahjong",
    "Tel-Tel Stadium",
    "Tetris",
    "Thunder Force II MD",
    "Thunder Force III",
    "Thunder Force IV",
    "Thunder Fox",
    "Thunder Pro Wrestling Retsuden",
    "Time Dominator 1st",
    "Toki no Keishousha - Phantasy Star III",
    "Tom and Jerry - Frantic Antics",
    "Top Pro Golf 2",
    "Top Pro Golf",
    "Tougiou King Colossus",
    "True Lies",
    "Turbo OutRun",
    "Twinkle Tale",
    "Uchuu Senkan Gomora",
    "Ultraman",
    "Undead Line",
    "V-V",
    "Valis III",
    "Vampire Killer",
    "Vermilion",
    "Verytex",
    "Virtua Racing",
    "Virtual Bart",
    "Vixen 357",
    "Volfied",
    "WWF Raw",
    "WWF Royal Rumble",
    "Wani Wani World",
    "Wardner no Mori Special",
    "Whip Rush - Wakusei Voltegas no Nazo",
    "Wimbledon Championship Tennis",
    "Winter Olympics (En,Fr,De,Es,It,Pt,Sv,No)",
    "Wizard of the Immortal",
    "Wonder Boy III - Monster Lair",
    "Wonder Boy V - Monster World III",
    "Wonder Library",
    "World Cup Soccer ~ World Championship Soccer",
    "Wrestle War",
    "Wrestleball",
    "XDR - X-Dazedly-Ray",
    "Ys - Wanderers from Ys",
    "Yu Yu Hakusho - Makyou Toitsusen",
    "Yu Yu Hakusho Gaiden",
    "Zan Yasha Enbukyoku",
    "Zero Wing",
    "Zoom!",
    "Zou! Zou! Zou! Rescue Daisakusen"
]