export const sgGGNATitles = [
    "5 in 1 Funpak",
    "Addams Family",
    "Adventures of Batman & Robin",
    "Aerial Assault",
    "Aladdin",
    "Alien 3",
    "Andre Agassi Tennis",
    "Arcade Classics",
    "Arch Rivals",
    "Arena - Maze of Death",
    "Ariel the Little Mermaid",
    "Asterix and the Great Rescue",
    "Ax Battler - A Legend of Golden Axe",
    "Ayrton Senna's Super Monaco GP II",
    "Baku Baku Animal",
    "Batman Forever",
    "Batman Returns",
    "Batter Up",
    "Battleship",
    "Battletoads",
    "Beavis and Butt-head",
    "Berenstain Bears' Camping Adventure",
    "Bonkers Wax Up!",
    "Bram Stoker's Dracula",
    "Bubble Bobble",
    "Bugs Bunny in Double Trouble",
    "Bust-A-Move",
    "Caesars Palace",
    "Captain America and the Avengers",
    "Casino Funpak",
    "Castle of Illusion Starring Mickey Mouse",
    "Chakan",
    "Chase H.Q.",
    "Chessmaster",
    "Chicago Syndicate",
    "Choplifter III",
    "Chuck Rock II - Son of Chuck",
    "Chuck Rock",
    "Cliffhanger",
    "Clutch Hitter",
    "Columns",
    "Cool Spot",
    "Cosmic Spacehead",
    "Crystal Warriors",
    "Cutthroat Island",
    "Deep Duck Trouble Starring Donald Duck",
    "Defenders of Oasis",
    "Desert Speedtrap starring Road Runner and Wile E. Coyote",
    "Desert Strike - Return to the Gulf",
    "Devilish",
    "Double Dragon",
    "Dr. Robotnik's Mean Bean Machine",
    "Dragon - The Bruce Lee Story",
    "Dragon Crystal",
    "Dynamite Headdy",
    "Earthworm Jim",
    "Ecco II - The Tides of Time",
    "Ecco the Dolphin",
    "Evander Holyfield's 'Real Deal' Boxing",
    "F-15 Strike Eagle",
    "F1",
    "FIFA International Soccer",
    "FIFA Soccer 96",
    "Fantastic Dizzy",
    "Fantasy Zone",
    "Fatal Fury Special",
    "Foreman for Real",
    "Frank Thomas Big Hurt Baseball",
    "Fred Couples Golf",
    "G-LOC Air Battle",
    "GP Rider",
    "Garfield - Caught in the Act",
    "Gear Works",
    "George Foreman's KO Boxing",
    "Greendog",
    "Halley Wars",
    "Home Alone",
    "Hook",
    "Incredible Crash Dummies",
    "Incredible Hulk",
    "Indiana Jones and the Last Crusade",
    "Iron Man X-O Manowar in Heavy Metal",
    "Itchy & Scratchy Game",
    "James Pond II - Codename RoboCod",
    "Jeopardy! - Sports Edition",
    "Jeopardy!",
    "Joe Montana Football",
    "Journey from Darkness - Strider Returns",
    "Judge Dredd",
    "Junction",
    "Jungle Book",
    "Jungle Strike",
    "Jurassic Park",
    "Kawasaki Superbike Challenge",
    "Klax",
    "Krusty's Fun House",
    "Land of Illusion Starring Mickey Mouse",
    "Last Action Hero",
    "Legend of Illusion Starring Mickey Mouse",
    "Lemmings",
    "Lion King",
    "Lost World - Jurassic Park",
    "Lucky Dime Caper",
    "MLBPA Baseball",
    "Madden NFL '95",
    "Madden NFL '96",
    "Magical Puzzle Popils",
    "Majors - Pro Baseball",
    "Marble Madness",
    "Mega Man",
    "Mick & Mack as the Global Gladiators",
    "Mickey's Ultimate Challenge",
    "Mighty Morphin Power Rangers - The Movie",
    "Mighty Morphin Power Rangers",
    "Monster Truck Wars",
    "Mortal Kombat II",
    "Mortal Kombat",
    "Ms. Pac-Man",
    "NBA Action Starring David Robinson",
    "NBA Jam Tournament Edition",
    "NBA Jam",
    "NFL '95",
    "NFL Quarterback Club '96",
    "NFL Quarterback Club",
    "NHL All-Star Hockey",
    "NHL Hockey",
    "Ninja Gaiden",
    "Olympic Gold",
    "OutRun Europa",
    "OutRun",
    "PGA Tour 96",
    "PGA Tour Golf II",
    "PGA Tour Golf",
    "Pac-Attack",
    "Pac-Man",
    "Paperboy II",
    "Paperboy",
    "Pengo",
    "Phantom 2040",
    "Pinball Dreams",
    "Poker Faced Paul's Blackjack",
    "Poker Faced Paul's Gin",
    "Poker Faced Paul's Poker",
    "Poker Faced Paul's Solitaire",
    "Predator 2",
    "Primal Rage",
    "Prince of Persia",
    "Psychic World",
    "Putt & Putter",
    "Quest for the Shaven Yak Starring Ren Hoek & Stimpy",
    "R.B.I. Baseball '94",
    "R.C. Grand Prix",
    "Revenge of Drancon",
    "Riddick Bowe Boxing",
    "Rise of the Robots",
    "Ristar",
    "Road Rash",
    "RoboCop 3",
    "RoboCop versus The Terminator",
    "Samurai Shodown",
    "Scratch Golf",
    "Shaq Fu",
    "Shining Force II - The Sword of Hajya",
    "Shinobi II - The Silent Fury",
    "Shinobi",
    "Side Pocket",
    "Simpsons - Bart vs. The Space Mutants",
    "Simpsons - Bart vs. The World",
    "Simpsons - Bartman Meets Radioactive Man",
    "Slider",
    "Solitaire Funpak",
    "Solitaire Poker",
    "Sonic Blast",
    "Sonic Chaos",
    "Sonic Labyrinth",
    "Sonic Spinball",
    "Sonic The Hedgehog - Triple Trouble",
    "Sonic The Hedgehog 2",
    "Sonic The Hedgehog",
    "Space Harrier",
    "Spider-Man - Return of the Sinister Six",
    "Spider-Man and the X-Men in Arcade's Revenge",
    "Spider-Man vs. The Kingpin",
    "Sports Illustrated Championship Football & Baseball",
    "Sports Trivia - Championship Edition",
    "Sports Trivia",
    "Star Trek - The Next Generation - The Advanced Holodeck Tutorial",
    "Star Trek Generations - Beyond the Nexus",
    "Star Wars",
    "Stargate",
    "Streets of Rage 2",
    "Streets of Rage",
    "Super Battletank",
    "Super Columns",
    "Super Golf",
    "Super Monaco GP",
    "Super Off Road",
    "Super Return of the Jedi",
    "Super Smash T.V.",
    "Super Space Invaders",
    "Surf Ninjas",
    "T2 - The Arcade Game",
    "Tails Adventures",
    "TaleSpin",
    "Taz in Escape from Mars",
    "Taz-Mania",
    "Tempo Jr.",
    "Tengen World Cup Soccer",
    "Terminator 2 - Judgment Day",
    "Terminator",
    "Tesserae",
    "Tom and Jerry - The Movie",
    "True Lies",
    "Urban Strike",
    "VR Troopers",
    "Vampire - Master of Darkness",
    "Virtua Fighter Animation",
    "WWF Raw",
    "WWF Wrestlemania Steel Cage Challenge",
    "Wheel of Fortune",
    "Wimbledon Tennis",
    "Winter Olympics - Lillehammer '94",
    "Woody Pop",
    "World Class Leader Board",
    "World Cup USA 94",
    "World Series Baseball '95",
    "World Series Baseball",
    "X-Men - Gamemaster's Legacy",
    "X-Men - Mojo World",
    "X-Men",
    "Zool - Ninja of the Nth Dimension",
    "Zoop"
]

export const sgGGEUTitles = [
    "Alien Syndrome",
    "Asterix and the Secret Mission",
    "CJ Elephant Fugitive",
    "Championship Hockey",
    "Cheese Cat-Astrophe - Starring Speedy Gonzales",
    "Daffy Duck in Hollywood",
    "Dropzone",
    "Ernie Els Golf",
    "Excellent Dizzy Collection",
    "F1 - World Championship Edition",
    "Factory Panic",
    "Galaga 2",
    "Hurricanes",
    "James Bond 007 - The Duel",
    "James Pond 3 - Operation Starfi5h",
    "Marko's Magic Football",
    "Master of Darkness",
    "Micro Machines 2 - Turbo Tournament",
    "Micro Machines",
    "Mortal Kombat 3",
    "Ottifants",
    "Pete Sampras Tennis",
    "Power Drive",
    "S.S. Lucifer - Man Overboard!",
    "Sega Game Pack 4 in 1",
    "Sensible Soccer - European Champions",
    "Smurfs Travel the World",
    "Smurfs",
    "Striker",
    "Superman - The Man of Steel",
    "Tarzan - Lord of the Jungle",
    "Tintin in Tibet",
    "Wizard Pinball",
    "Wolfchild",
    "Wonder Boy - The Dragon's Trap",
    "Wonder Boy"
]

export const sgGGJPNTitles = [
    "Aa Harimanada",
    "Berlin no Kabe",
    "Bishoujo Senshi Sailor Moon S",
    "Buster Ball",
    "Buster Fight",
    "Coca-Cola Kid",
    "Crayon Shin-chan - Taiketsu! Kantam Panic!!",
    "Donald no Magical World",
    "Doraemon - Noranosuke no Yabou",
    "Doraemon - Waku Waku Pocket Paradise",
    "Dunk Kids",
    "Eternal Legend",
    "Faceball 2000",
    "Fray - Shugyouhen",
    "From TV Animation - Slam Dunk - Shouri e no Starting 5",
    "GG Aleste",
    "GG Portrait - Pai Chan",
    "GG Portrait - Yuuki Akira",
    "Gamble Panic",
    "Gambler Jiko Chuushinha",
    "Ganbare Gorby!",
    "Gear Stadium Heiseiban",
    "Godzilla Kaijuu Daishingeki",
    "Griffin",
    "Gunstar Heroes",
    "Head Buster",
    "Honoo no Toukyuuji Dodge Danpei",
    "House of Tarot",
    "Hyokkori Hyoutan-Jima - Hyoutan-Jima no Daikoukai",
    "Hyper Pro Yakyuu '92",
    "Ichidant~R GG",
    "J-League GG Pro Striker '94",
    "J-League Soccer - Dream Eleven",
    "Kaitou Saint Tail",
    "Kenyuu Densetsu Yaiba",
    "Kinetic Connection",
    "Kishin Douji Zenki",
    "Kuni Chan no Game Tengoku - Part 2",
    "Kuni Chan no Game Tengoku",
    "Lunar - Sanposuru Gakuen",
    "Madou Monogatari A - Doki Doki Vacation",
    "Madou Monogatari I - 3-Tsu no Madoukyuu",
    "Madou Monogatari II - Arle 16-Sai",
    "Madou Monogatari III - Kyuukyoku Joou-sama",
    "Magic Knight Rayearth 2 - Making of Magic Knight",
    "Magic Knight Rayearth",
    "Magical Taruruuto-kun",
    "Mappy",
    "Megami Tensei Gaiden - Last Bible Special",
    "Megami Tensei Gaiden - Last Bible",
    "Moldorian - Hikari to Yami no Sister",
    "Nazo Puyo 2",
    "Nazo Puyo Arle no Roux",
    "Nazo Puyo",
    "Neko Dai Suki!",
    "Ninkuu 2 - Tenkuryu-e no Michi",
    "Ninkuu Gaiden - Hiroyuki Daikatsugeki",
    "Ninkuu",
    "Panzer Dragoon Mini",
    "Pet Club Inu Dai Suki!",
    "Phantasy Star Adventure",
    "Phantasy Star Gaiden",
    "Pocket Jansou",
    "Pop Breaker",
    "Popeye no Beach Volleyball",
    "Power Strike II",
    "Pro Yakyuu '91",
    "Pro Yakyuu GG League '94",
    "Pro Yakyuu GG League",
    "Puyo Puyo 2",
    "Puyo Puyo",
    "Puzzle & Action - Tant-R",
    "Rastan Saga",
    "Royal Stone - Hirakareshi Toki no Tobira",
    "SD Gundam - Winner's History",
    "Shanghai II",
    "Shikinjou",
    "Shining Force Gaiden - Ensei Jashin no Kuni e",
    "Shining Force Gaiden - Final Conflict",
    "Sonic Drift",
    "Soukoban",
    "Super Momotarou Dentetsu III",
    "Sylvan Tale",
    "Tails no Sky Patrol",
    "Taisen Mahjong HaoPai 2",
    "Taisen Mahjong HaoPai",
    "Taisen-gata Daisenryaku G",
    "Tama & Friends - 3 Choume Kouen Tamalympic",
    "Tatakae! Pro Yakyuu Twin League",
    "The Quiz Gear Fight!!",
    "Torarete Tamaruka!",
    "Ultimate Soccer",
    "Wagan Land",
    "Wagyan Land",
    "World Derby",
    "Yu Yu Hakusho - Horobishimono no Gyakushuu",
    "Yu Yu Hakusho 2 - Gekitou! Nanakyou no Tatakai",
    "Zan Gear"
]