export const sgMSNATitles = [
    "Action Fighter",
    "Aerial Assault",
    "After Burner",
    "Alex Kidd - High-Tech World",
    "Alex Kidd - The Lost Stars",
    "Alex Kidd in Miracle World",
    "Alex Kidd in Shinobi World",
    "Alf",
    "Alien Syndrome",
    "Altered Beast",
    "Aztec Adventure - The Golden Road to Paradise",
    "Black Belt",
    "Blade Eagle",
    "Bomber Raid",
    "Bruce Lee",
    "California Games",
    "Captain Silver",
    "Casino Games",
    "Castle of Illusion Starring Mickey Mouse",
    "Choplifter",
    "Cloud Master",
    "Columns",
    "Cyborg Hunter",
    "Dead Angle",
    "Dick Tracy",
    "Double Dragon",
    "E-SWAT - City Under Siege",
    "Enduro Racer",
    "F-16 Fighting Falcon",
    "Fantasy Zone - The Maze",
    "Fantasy Zone II - The Tears of Opa-Opa",
    "Fantasy Zone",
    "Galaxy Force",
    "Gangster Town",
    "Ghost House",
    "Ghostbusters",
    "Ghouls'n Ghosts",
    "Global Defense",
    "Golden Axe Warrior",
    "Golden Axe",
    "Golvellius",
    "Great Baseball",
    "Great Basketball",
    "Great Football",
    "Great Golf",
    "Great Soccer",
    "Great Volleyball",
    "Hang-On & Astro Warrior",
    "Hang-On & Safari Hunt",
    "James 'Buster' Douglas Knockout Boxing",
    "Joe Montana Football",
    "Kenseiden",
    "King's Quest - Quest for the Crown",
    "Kung Fu Kid",
    "Lander 2",
    "Lord of the Sword",
    "Marksman Shooting & Trap Shooting",
    "Maze Hunter 3-D",
    "Michael Jackson's Moonwalker",
    "Miracle Warriors - Seal of the Dark Lord",
    "Missile Defense 3-D",
    "Monopoly",
    "Montezuma's Revenge Featuring Panama Joe",
    "My Hero",
    "Ninja",
    "Out Run",
    "OutRun",
    "Paperboy",
    "Parlour Games",
    "Pat Riley Basketball (Proto)",
    "Penguin Land",
    "Phantasy Star",
    "Poseidon Wars 3-D",
    "Power Strike",
    "Pro Wrestling",
    "Psycho Fox",
    "Quartet",
    "R-Type",
    "R.C. Grand Prix",
    "Rambo - First Blood Part II",
    "Rambo III",
    "Rampage",
    "Rastan",
    "Reggie Jackson Baseball",
    "Rescue Mission",
    "Rocky",
    "Shanghai",
    "Shinobi",
    "Shooting Gallery",
    "Slap Shot",
    "Sonic The Hedgehog",
    "Space Harrier 3-D",
    "Space Harrier",
    "SpellCaster",
    "Spider-Man vs. The Kingpin",
    "Sports Pad Football",
    "Spy vs. Spy",
    "Strider",
    "Super Monaco GP",
    "Super Tennis",
    "Teddy Boy",
    "Thunder Blade",
    "Time Soldiers",
    "TransBot",
    "Vigilante",
    "Walter Payton Football",
    "Wanted",
    "Where in the World is Carmen Sandiego",
    "Wonder Boy III - The Dragon's Trap",
    "Wonder Boy in Monster Land",
    "Wonder Boy",
    "World Grand Prix",
    "Ys - The Vanished Omens",
    "Zaxxon 3-D",
    "Zillion II - The Tri Formation",
    "Zillion"
]

export const sgMSEUTitles = [
    "Ace of Aces",
    "Addams Family",
    "Air Rescue",
    "Aladdin",
    "Alien 3",
    "Alien Storm",
    "American Baseball",
    "American Pro Football",
    "Andre Agassi Tennis",
    "Arcade Smash Hits",
    "Assault City",
    "Asterix and the Great Rescue",
    "Asterix and the Secret Mission",
    "Asterix",
    "Astro Warrior & Pit Pot",
    "Ayrton Senna's Super Monaco GP II",
    "Back to the Future Part II",
    "Back to the Future Part III",
    "Bank Panic",
    "Basket Ball Nightmare",
    "Basketball Nightmare",
    "Batman Returns",
    "Battle Out Run",
    "Battle OutRun",
    "Bonanza Bros.",
    "Bram Stoker's Dracula",
    "Bubble Bobble",
    "Buggy Run",
    "California Games II",
    "Champions of Europe",
    "Championship Hockey",
    "Cheese Cat-astrophe Starring Speedy Gonzales",
    "Chuck Rock II - Son of Chuck",
    "Chuck Rock",
    "Cool Spot",
    "Cosmic Spacehead",
    "Cyber Shinobi",
    "Daffy Duck in Hollywood (En,Fr,De,Es,It)",
    "Daffy Duck in Hollywood",
    "Danan - The Jungle Fighter",
    "Deep Duck Trouble Starring Donald Duck",
    "Desert Speedtrap Starring Road Runner and Wile E. Coyote",
    "Desert Strike",
    "Double Hawk",
    "Dr. Robotnik's Mean Bean Machine",
    "Dragon - The Bruce Lee Story",
    "Dragon Crystal",
    "Dynamite Duke",
    "Dynamite Dux",
    "Ecco the Dolphin",
    "F1",
    "Fantastic Dizzy",
    "Fire & Forget II",
    "Flash",
    "Flintstones",
    "Forgotten Worlds",
    "G-LOC Air Battle",
    "GP Rider",
    "Gain Ground",
    "Gauntlet",
    "George Foreman's KO Boxing",
    "Golfamania",
    "Great Soccer",
    "Hang-On",
    "Heavyweight Champ",
    "Heroes of the Lance",
    "Home Alone",
    "Impossible Mission",
    "Incredible Crash Dummies",
    "Incredible Hulk",
    "Indiana Jones and the Last Crusade",
    "James Bond 007 - The Duel",
    "James Pond 2 - Codename RoboCod",
    "Jungle Book",
    "Jurassic Park",
    "Klax",
    "Krusty's Fun House",
    "Land of Illusion Starring Mickey Mouse",
    "Laser Ghost",
    "Lemmings",
    "Line of Fire",
    "Lion King",
    "Lucky Dime Caper Starring Donald Duck",
    "Marble Madness",
    "Marksman Shooting & Trap Shooting & Safari Hunt",
    "Master of Darkness",
    "Masters of Combat",
    "Mercs",
    "Mick & Mack as the Global Gladiators",
    "Micro Machines",
    "Mortal Kombat II",
    "Mortal Kombat",
    "Ms. Pac-Man",
    "New Zealand Story",
    "Ninja Gaiden",
    "Olympic Gold",
    "Operation Wolf",
    "Ottifants",
    "Out Run 3-D",
    "Out Run Europa",
    "OutRun 3-D",
    "OutRun Europa",
    "PGA Tour Golf",
    "Pac-Mania",
    "Pit Fighter",
    "Populous",
    "Power Strike II",
    "Predator 2",
    "Prince of Persia",
    "Psychic World",
    "Putt & Putter",
    "Rainbow Islands - The Story of Bubble Bobble 2",
    "Rampart",
    "Renegade",
    "Road Rash",
    "RoboCop 3",
    "RoboCop versus The Terminator",
    "Running Battle",
    "Sagaia",
    "Scramble Spirits",
    "Sega Chess",
    "Sega World Tournament Golf",
    "Sensible Soccer",
    "Shadow Dancer - The Secret of Shinobi",
    "Shadow Dancer",
    "Shadow of the Beast",
    "Simpsons - Bart vs. The Space Mutants",
    "Simpsons - Bart vs. The World",
    "Smurfs - Travel the World",
    "Smurfs",
    "Snail Maze",
    "Sonic Chaos",
    "Sonic Spinball",
    "Sonic The Hedgehog 2",
    "Space Gun",
    "Special Criminal Investigation",
    "Speedball 2",
    "Speedball",
    "Spider-Man - Return of the Sinister Six",
    "Star Wars",
    "Streets of Rage II",
    "Streets of Rage",
    "Strider II",
    "Submarine Attack",
    "Summer Games",
    "Super Kick Off",
    "Super Monaco GP II",
    "Super Off Road",
    "Super Smash T.V.",
    "Super Space Invaders",
    "Superman - The Man of Steel",
    "T2 - The Arcade Game",
    "Taito Chase H.Q.",
    "Taz-Mania",
    "Tecmo World Cup '93",
    "Tennis Ace",
    "Terminator 2 - Judgment Day",
    "Terminator",
    "Tom and Jerry - The Movie",
    "Trivial Pursuit - Genus Edition (En,Fr,De,Es)",
    "Trivial Pursuit - Genus Edition",
    "Ultima IV - Quest of the Avatar",
    "Ultimate Soccer",
    "WWF Wrestlemania - Steel Cage Challenge",
    "Wimbledon II",
    "Wimbledon",
    "Winter Olympics - Lillehammer '94",
    "Wolfchild",
    "Wonder Boy in Monster World",
    "World Class Leader Board",
    "World Cup Italia '90",
    "World Cup USA 94",
    "World Games",
    "Xenon 2 - Megablast",
    "Zillion",
    "Zool - Ninja of the 'Nth' Dimension"
]

export const sgMSJPNTitles = [
    "Alex Kidd BMX Trial",
    "Argos no Juujiken",
    "Comical Machine Gun Joe",
    "Galactic Protector",
    "Gekioko PunPun Maru",
    "Great Baseball",
    "Great Golf",
    "High School! Kimengumi",
    "Hokuto no Ken",
    "Hoshi wo Sagasite...",
    "Mahjong Sengoku Jidai",
    "Megumi Rescue",
    "Nekkyuu Koushien",
    "Pro Yakyuu Pennant Race",
    "Satellite 7",
    "Solomon no Kagi - Oujo Rihita no Namida",
    "Sukeban Deka II - Shoujo Tekkamen Densetsu",
    "Super Racing",
    "Woody Pop - Shinjinrui no Block Kuzushi"
]

export const sgMSBRZTitles = [
    "20 em 1",
    "Ariel - The Little Mermaid",
    "Baku Baku",
    "Battlemaniacs",
    "Bonkers Wax Up!",
    "Castelo Ra-Tim-Bum",
    "Chapolim x Dracula - Um Duelo Assustador",
    "Dynamite Headdy",
    "Earthworm Jim",
    "Ecco - The Tides of Time",
    "FIFA International Soccer",
    "Ferias Frustradas Do Pica-Pau",
    "Fire & Ice",
    "Geraldinho",
    "Legend of Illusion Starring Mickey Mouse",
    "Mickey's Ultimate Challenge",
    "Monica no Castelo do Dragao",
    "Mortal Kombat 3",
    "Quest for the Shaven Yak Starring Ren Hoek & Stimpy",
    "Sapo Xule - O Mestre do Kung Fu",
    "Sapo Xule - S.O.S Lagoa Poluida",
    "Sapo Xule vs. Os Invasores do Brejo",
    "Sitio Do Pica pau Amarelo",
    "Sonic Blast",
    "Street Fighter II",
    "TV Colosso",
    "Taz in Escape from Mars",
    "Virtua Fighter Animation",
    "Wonder Boy III The Dragon's Trap",
    "X-Men - Mojo World"
]