export const sgSatNATitles =  [
    "3D Baseball",
    "A+M+O+K",
    "Albert Odyssey - Legend of Eldean",
    "Alien Trilogy",
    "All Star Baseball '97 Featuring Frank Thomas",
    "Alone in the Dark - One-Eyed Jack's Revenge",
    "Andretti Racing",
    "Arcade's Greatest Hits - The Atari Collection 1",
    "Arcade's Greatest Hits - Williams",
    "Area 51",
    "Astal",
    "Baku Baku",
    "Bases Loaded '96 - Double Header",
    "Batman Forever - The Arcade Game",
    "Battle Arena Toshinden Remix",
    "Battle Arena Toshinden URA",
    "Battle Monsters",
    "Battle Stations",
    "BattleSport",
    "Black Dawn",
    "Black Fire",
    "Blast Chamber",
    "Blazing Dragons",
    "Blazing Heroes",
    "Bottom of the 9th",
    "Brain Dead 13",
    "Break Point Tennis",
    "Bubble Bobble - Also featuring Rainbow Islands",
    "Bug Too!",
    "Bug!",
    "Burning Rangers",
    "Bust-A-Move 2 - Arcade Edition",
    "Bust-A-Move 3",
    "Casper",
    "Center Ring Boxing",
    "Christmas Nights into Dreams...",
    "Clockwork Knight 2",
    "Clockwork Knight",
    "College Slam",
    "Command & Conquer",
    "Congo - The Movie - The Lost City Of Zinj",
    "Contra - Legacy of War",
    "Corpse Killer - Graveyard Edition",
    "Courier Crisis",
    "Creature Shock",
    "Crime Wave",
    "Criticom - The Critical Combat",
    "Croc - Legend of the Gobbos",
    "Crow - City of Angels",
    "Crusader - No Remorse",
    "Crypt Killer",
    "Cyber Speedway",
    "Cyberia",
    "D",
    "Darius Gaiden",
    "Dark Legend",
    "Dark Savior",
    "Darklight Conflict",
    "Daytona USA - Championship Circuit Edition",
    "Daytona USA",
    "Decathlete",
    "Defcon 5",
    "Die Hard Arcade",
    "Die Hard Trilogy",
    "Doom",
    "Double Switch",
    "Dragon Force",
    "DragonHeart - Fire & Steel",
    "Earthworm Jim 2",
    "Enemy Zero",
    "F1 Challenge",
    "FIFA - Road to World Cup 98",
    "FIFA Soccer 96",
    "FIFA Soccer 97",
    "Fighters Megamix",
    "Fighting Vipers",
    "Frank Thomas Big Hurt Baseball",
    "Galactic Attack",
    "Galaxy Fight",
    "Gex",
    "Ghen War",
    "Golden Axe - The Duel",
    "Grand Slam",
    "Grid Runner",
    "Guardian Heroes",
    "Gungriffon",
    "Hang-On GP",
    "Heir of Zendor - The Legend and The Land",
    "Herc's Adventures",
    "Hexen - Beyond Heretic",
    "Hi-Octane - The Track Fights Back!",
    "High Velocity - Mountain Racing Challenge",
    "Highway 2000",
    "Horde",
    "House of the Dead",
    "Hyper 3-D Pinball",
    "Impact Racing",
    "In the Hunt",
    "Incredible Hulk - The Pantheon Saga",
    "Independence Day",
    "Iron Man X-O Manowar in Heavy Metal",
    "Iron Storm",
    "Johnny Bazookatone",
    "Last Bronx",
    "Last Gladiators - Digital Pinball",
    "Legend of Oasis",
    "Loaded",
    "Lost World - Jurassic Park",
    "Lunacy",
    "Machine Head",
    "Madden NFL 97",
    "Madden NFL 98",
    "Magic Carpet",
    "Magic Knight Rayearth",
    "Mansion of Hidden Souls",
    "Manx TT SuperBike",
    "Marvel Super Heroes",
    "Mass Destruction",
    "Maximum Force",
    "MechWarrior 2 - 31st Century Combat",
    "Mega Man 8 - Anniversary Collector's Edition",
    "Megaman X4",
    "Minnesota Fats - Pool Legend",
    "Mortal Kombat II",
    "Mortal Kombat Trilogy",
    "Mr. Bones",
    "Myst",
    "Mystaria - The Realms of Lore?",
    "NASCAR '98",
    "NBA Action 98",
    "NBA Action",
    "NBA Jam Extreme",
    "NBA Jam Tournament Edition",
    "NBA Live 97",
    "NBA Live 98",
    "NFL '97",
    "NFL Quarterback Club '96",
    "NFL Quarterback Club '97",
    "NHL 97",
    "NHL 98",
    "NHL All-Star Hockey 98",
    "NHL All-Star Hockey",
    "NHL Powerplay '96",
    "Need for Speed",
    "Netlink Internet Browser 2.0",
    "Netlink Internet Browser 3.0",
    "Night Warriors - Darkstalkers' Revenge",
    "Nights Into Dreams...",
    "Norse by Norsewest - The Return of The Lost Vikings",
    "Off-World Interceptor Extreme",
    "Olympic Soccer",
    "P.T.O. II - Pacific Theater of Operations",
    "PGA Tour 97",
    "Pandemonium!",
    "Panzer Dragoon II - Zwei",
    "Panzer Dragoon Saga",
    "Panzer Dragoon",
    "Pebble Beach Golf Links",
    "PowerSlave",
    "Primal Rage",
    "Pro Pinball",
    "Quake",
    "Quarterback Attack with Mike Ditka",
    "Rampage - World Tour",
    "Rayman",
    "Resident Evil",
    "Resurrection - Rise 2",
    "Return Fire",
    "Revolution X",
    "Road Rash",
    "Robo Pit",
    "Robotica",
    "Romance of the Three Kingdoms IV - Wall Of Fire",
    "Scorcher",
    "Scud - The Disposable Assassin",
    "Sega Ages",
    "Sega Rally Championship - NetLink Edition",
    "Sega Rally Championship",
    "Sega Saturn Choice Cuts v2.0",
    "Sega Screams Volume 1",
    "Sega Touring Car Championship",
    "Sega Worldwide Soccer '97",
    "Sega Worldwide Soccer '98",
    "Shanghai - Triple Threat",
    "Shellshock",
    "Shining Force III",
    "Shining Wisdom",
    "Shining the Holy Ark",
    "Shinobi Legions",
    "Shockwave Assault",
    "SimCity 2000",
    "Skeleton Warriors",
    "Sky Target",
    "Slam 'N Jam '96 featuring Magic & Kareem",
    "Solar Eclipse",
    "Sonic 3D Blast",
    "Sonic Jam",
    "Sonic R",
    "Soviet Strike",
    "Space Hulk - Vengeance of the Blood Angels",
    "Space Jam",
    "Spot Goes to Hollywood",
    "Star Fighter",
    "Steep Slope Sliders",
    "Street Fighter - The Movie",
    "Street Fighter Alpha - Warrior's Dreams",
    "Street Fighter Alpha 2",
    "Street Fighter Collection",
    "Striker '96",
    "Super Puzzle Fighter II Turbo",
    "TNN Motor Sports - Hardcore 4X4",
    "Tempest 2000",
    "Ten Pin Alley",
    "Tetris Plus",
    "Theme Park",
    "Three Dirty Dwarves",
    "Thunderstrike 2",
    "Tomb Raider",
    "True Pinball",
    "Tunnel B1",
    "Ultimate Mortal Kombat 3",
    "VR Golf '97",
    "VR Soccer",
    "VR Virtua Racing",
    "Valora Valley Golf",
    "Virtua Cop 2",
    "Virtua Cop",
    "Virtua Fighter 2",
    "Virtua Fighter Kids",
    "Virtua Fighter Remix",
    "Virtua Fighter",
    "Virtua On",
    "Virtual Casino",
    "Virtual Hydlide",
    "Virtual On - Cyber Troopers-01",
    "Virtual Open Tennis",
    "WWF In Your House",
    "WWF Wrestlemania - The Arcade Game",
    "WarCraft II - The Dark Saga",
    "Wing Arms",
    "Winning Post",
    "Winter Heat",
    "WipEout",
    "World Cup Golf - Professional Edition",
    "World Series Baseball '98",
    "World Series Baseball II",
    "World Series Baseball",
    "Worldwide Soccer - Sega International Victory Goal Edition",
    "Worms",
    "X-Men - Children of the Atom"
]

export const sgSatEUTitles = [
    "3D Lemmings",
    "Actua Golf",
    "Actua Soccer - Club Edition",
    "Alien Trilogy",
    "Alone in the Dark - Jack Is Back",
    "Amok",
    "Andretti Racing",
    "Arcade's Greatest Hits - The Atari Collection 1",
    "Area 51",
    "Athlete Kings",
    "Atlantis - The Lost Tales",
    "Baku Baku Animal - World Zookeeper Contest",
    "Batman Forever - The Arcade Game",
    "Battle Arena Toshinden Remix",
    "Battle Arena Toshinden URA - Ultimate Revenge Attack",
    "Battle Monsters",
    "Battle Stations",
    "Black Dawn",
    "Black Fire",
    "Blam! Machinehead",
    "Blast Chamber",
    "Blazing Dragons",
    "Break Point",
    "Bubble Bobble also featuring Rainbow Islands",
    "Bug Too!",
    "Bug!",
    "Burning Rangers",
    "Bust-A-Move 2 - Arcade Edition",
    "Bust-A-Move 3",
    "Casper",
    "Chaos Control",
    "Christmas NiGHTS into Dreams...",
    "Clockwork Knight - Pepperouchau's Adventure",
    "Clockwork Knight 2 - Pepperouchau's Adventure",
    "Command & Conquer",
    "Courier Crisis - The Saga of the Modern Fatalist",
    "Crimewave",
    "Croc - Legend of the Gobbos",
    "Crow - City of Angels",
    "Crusader - No Remorse",
    "Crypt Killer",
    "Cyber Speedway",
    "Cyberia",
    "D",
    "Darius Gaiden",
    "Darius II",
    "Dark Savior",
    "Darklight Conflict",
    "Daytona USA - Championship Circuit Edition",
    "Daytona USA",
    "Deep Fear",
    "Defcon 5",
    "Destruction Derby",
    "Die Hard Arcade",
    "Die Hard Trilogy",
    "Digital Pinball",
    "Discworld II - Missing Presumed...!",
    "Doom",
    "Dragon Ball Z - La Grande Legende des Boules de Cristal",
    "Dragon Force",
    "DragonHeart - Fire & Steel",
    "Duke Nukem 3D",
    "Earthworm Jim 2",
    "Enemy Zero",
    "Exhumed",
    "F-1 Challenge",
    "FIFA - Road to World Cup 98",
    "FIFA 97",
    "FIFA Soccer 96",
    "Fighters Megamix",
    "Fighting Vipers",
    "Firestorm - Thunderhawk 2",
    "Formula Karts - Special Edition",
    "Frank Thomas Big Hurt Baseball",
    "Frankenstein - Through the Eyes of the Monster",
    "Galactic Attack",
    "Galaxy Fight",
    "Gex",
    "Ghen War",
    "Golden Axe - The Duel",
    "Grid Run",
    "Guardian Heroes",
    "Gun Griffon",
    "Hang On GP '96",
    "Hardcore 4x4",
    "Hebereke's Popoitto",
    "Hexen",
    "Hi-Octane",
    "Highway 2000",
    "Horde",
    "House of the Dead",
    "Impact Racing",
    "In the Hunt",
    "Incredible Hulk - The Pantheon Saga",
    "Independence Day - The Game",
    "International Victory Goal",
    "Iron Man & X-O Manowar in Heavy Metal",
    "Jewels of the Oracle",
    "Johnny Bazookatone",
    "Jonah Lomu Rugby",
    "Keio Flying Squadron 2",
    "King of Fighters '95",
    "Krazy Ivan",
    "Last Bronx",
    "Loaded",
    "Lost Vikings 2 - Norse by Norsewest",
    "Lost World - Jurassic Park",
    "Madden NFL 97",
    "Madden NFL 98",
    "Magic Carpet",
    "Mansion of Hidden Souls",
    "Manx TT SuperBike",
    "Marvel Super Heroes",
    "Mass Destruction",
    "Maximum Force",
    "MechWarrior 2 - 31st Century Combat - Arcade Combat Edition",
    "Mega Man X3",
    "Mighty Hits",
    "Mortal Kombat II",
    "Mortal Kombat Trilogy",
    "Mr. Bones",
    "Myst (En,Fr,De,Es)",
    "Mystaria - The Realms of Lore",
    "NASCAR 98",
    "NBA Action 98",
    "NBA Action",
    "NBA Jam - Tournament Edition",
    "NBA Jam Extreme",
    "NBA Live 97",
    "NBA Live 98",
    "NFL Quarterback Club 96",
    "NFL Quarterback Club 97",
    "NHL 97",
    "NHL 98",
    "NHL All-Star Hockey 98",
    "NHL All-Star Hockey",
    "NHL Powerplay '96",
    "NiGHTS into Dreams...",
    "Night Warriors - Darkstalkers' Revenge",
    "Off-World Interceptor Extreme",
    "Olympic Soccer",
    "PGA Tour 97",
    "Pandemonium!",
    "Panzer Dragoon II Zwei",
    "Panzer Dragoon Saga",
    "Panzer Dragoon",
    "Parodius",
    "Pebble Beach Golf Links",
    "Pinball Graffiti",
    "Primal Rage",
    "Pro-Pinball - The Web",
    "Quake",
    "Rampage - World Tour",
    "Rayman",
    "Resident Evil",
    "Revolution X - Music Is the Weapon",
    "Rise 2 - Resurrection",
    "Riven - The Sequel to Myst",
    "Road & Track Presents - The Need for Speed",
    "Road Rash",
    "Robo Pit",
    "Robotica - Cybernation Revolt",
    "Saturn Bomberman",
    "Scorcher",
    "Sea Bass Fishing",
    "Sega Ages Volume 1",
    "Sega Rally Championship",
    "Sega Touring Car Championship",
    "Sega Worldwide Soccer '98 - Club Edition",
    "Sega Worldwide Soccer 97",
    "Shellshock",
    "Shining Force III",
    "Shining Wisdom",
    "Shining the Holy Ark",
    "Shinobi-X - Shin Shinobi Den",
    "Shockwave Assault",
    "SimCity 2000",
    "Skeleton Warriors",
    "Sky Target",
    "Slam 'n Jam '96 featuring Magic & Kareem - Signature Edition",
    "Sonic 3D - Flickies' Island",
    "Sonic Jam",
    "Sonic R",
    "Soviet Strike",
    "Space Hulk - Vengeance of the Blood Angels",
    "Space Jam",
    "Spot Goes to Hollywood",
    "StarFighter 3000",
    "Steep Slope Sliders",
    "Story of Thor 2",
    "Street Fighter - The Movie",
    "Street Fighter Alpha - Warriors' Dreams",
    "Street Fighter Alpha 2",
    "Street Fighter Collection",
    "Street Racer",
    "Striker 96",
    "Super Puzzle Fighter II Turbo",
    "Swagman",
    "Tempest 2000",
    "Terry Pratchett's Discworld",
    "Tetris Plus",
    "Theme Park",
    "Three Dirty Dwarves",
    "Thunderhawk 2 - Firestorm",
    "Tilt!",
    "Titan Wars",
    "Tomb Raider",
    "Torico",
    "Trash It (En,Fr,De,Es,It)",
    "True Pinball",
    "Tunnel B1 (En,Fr,De,Es,It)",
    "UEFA Euro 96 - England (En,Fr,De,Es,It,Pt)",
    "Ultimate Mortal Kombat 3",
    "Valora Valley Golf",
    "Victory Boxing",
    "Virtua Cop 2",
    "Virtua Cop",
    "Virtua Fighter 2",
    "Virtua Fighter CG Portrait Collection",
    "Virtua Fighter Kids",
    "Virtua Fighter Remix",
    "Virtua Fighter",
    "Virtua Racing",
    "Virtual Golf",
    "Virtual Hydlide",
    "Virtual On - Cyber Troopers",
    "Virtual Open Tennis",
    "WWF In Your House",
    "WWF WrestleMania - The Arcade Game",
    "WarCraft II - The Dark Saga",
    "Whizz",
    "Wing Arms",
    "Winter Heat",
    "WipEout 2097",
    "WipEout",
    "World Cup Golf - Professional Edition",
    "World League Soccer '98",
    "World Series Baseball II",
    "World Series Baseball",
    "Worms",
    "X-Men - Children of the Atom",
    "Z"
]

export const sgSatJPNTitles = [
    "2Tax Gold",
    "2do Aru Koto wa Sando R",
    "3D Baseball - The Majors",
    "3D Lemmings",
    "3D Mission Shooting - Finalist",
    "3x3 Eyes - Kyuusei Koushu S",
    "6 Inch My Darling",
    "AI Igo",
    "AI Shougi 2",
    "AI Shougi",
    "Actua Golf",
    "Actua Soccer",
    "Advanced V.G.",
    "Advanced World War - Sennen Teikoku no Koubou - Last of the Millennium",
    "Ai Iijima Interactive Video Clip - Good Island Cafe",
    "Air Management '96",
    "Airs Adventure",
    "Akumajou Dracula X - Gekka no Yasoukyoku",
    "Albert Odyssey Gaiden - Legend of Eldean",
    "Album Club (Mune Kyun) - St. Paulia Jogakuin",
    "Alien Trilogy",
    "Alone in the Dark 2",
    "Amagi Shien",
    "America Oudan Ultra Quiz",
    "Amok",
    "AnEarth Fantasy Stories - The First Volume",
    "Angel Graffiti S - Anata e no Profile",
    "Angel Paradise Vol. 1 - Sakaki Yuko - Koi no Yokan in Hollywood",
    "Angel Paradise Vol. 2 - Yoshino Kimika - Isshoni I-ta-i in Hawaii",
    "Angelique Duet",
    "Angelique Special 2",
    "Angelique Special",
    "Another Memories",
    "Aqua-world - Umimi Monogatari",
    "Aquazone - Desktop Life Option Disc Series 1 - Angel Fish",
    "Aquazone - Desktop Life Option Disc Series 2 - Black Molly",
    "Aquazone - Desktop Life Option Disc Series 3 - Blue Emperor",
    "Aquazone - Desktop Life Option Disc Series 4 - Clown Loach",
    "Aquazone - Desktop Life Option Disc Series 5 - False Rummy-Nose",
    "Aquazone - Desktop Life",
    "Arcade Gears Vol. 1 - Pu-Li-Ru-La",
    "Arcade Gears Vol. 2 - Gun Frontier",
    "Arcade Gears Vol. 3 - Wonder 3",
    "Arcade Gears Vol. 4 - ImageFight & XMultiply",
    "Arcana Strikes",
    "Area 51",
    "Arthur to Astaroth no Nazo Makaimura - Incredible Toons",
    "Assault Rigs",
    "Assault Suit Leynos 2",
    "Astra Superstars",
    "Asuka 120% Limited - Burning Fest. Limited",
    "Ayakashi Ninden Kunoichiban Plus",
    "Ayrton Senna Personal Talk - Message for the Future",
    "Azel - Panzer Dragoon RPG",
    "BackGuiner - Yomigaeru Yuusha-tachi - Hishou-hen - Uragiri no Senjou",
    "BackGuiner - Yomigaeru Yuusha-tachi - Kakusei-hen - Guiner Tensei",
    "Baku Baku Animal - Sekai Shiiku Gakari Senshuken",
    "Bakuretsu Hunter R",
    "Bakuretsu Hunter",
    "Bakushou!! All Yoshimoto Quiz-ou Kettei-sen DX",
    "Baldy Land",
    "Baroque",
    "Batman Forever - The Arcade Game",
    "Batsugun",
    "Battle Athletess Daiundoukai",
    "Battle Garegga",
    "Battle Monsters",
    "Beach de Riichi!",
    "Big Ichigeki! Pachi-Slot Daikouryaku - Universal Museum",
    "Big Thanks - Super Keirin - Dream with Keirin 50 Years",
    "Bio Hazard",
    "Bishoujo Hanafuda Kikou - Michinoku Hitou Koi Monogatari Special",
    "Bishoujo Senshi Sailor Moon SuperS - Various Emotion",
    "Black Dawn",
    "Black Fire",
    "Black Matrix",
    "Blam! Machinehead",
    "Blast Wind",
    "Blood Factory",
    "Blue Breaker - Ken Yori mo Hohoemi o",
    "Blue Seed - Kushinada Hirokuden",
    "Bomberman Wars",
    "Bouken Katsugeki Monomono",
    "Brain Battle Q",
    "Brain Dead 13",
    "Break Point",
    "BreakThru!",
    "Bubble Symphony",
    "Bug Too! Motto Motto Jump Shite, Funzukechatte, Petchanko",
    "Bug! Jump Shite, Funzukechatte, Petchanko",
    "Bulk Slash",
    "Burning Rangers",
    "Can Can Bunny Extra",
    "Can Can Bunny Premiere 2",
    "Can Can Bunny Premiere",
    "Capcom Generation - Dai-1-shuu Gekitsuiou no Jidai",
    "Capcom Generation - Dai-2-shuu Makai to Kishi",
    "Capcom Generation - Dai-3-shuu Koko ni Rekishi Hajimaru",
    "Capcom Generation - Dai-4-shuu Kokou no Eiyuu",
    "Capcom Generation - Dai-5-shuu Kakutouka-tachi",
    "Casper",
    "Cat the Ripper - 13Ninme no Tanteishi",
    "Chaos Control Remix",
    "Chaos Control",
    "Chibi Maruko-chan no Taisen Puzzle-dama",
    "Chisato Moritaka - Watarase Bashi & Lala Sunshine",
    "Cho Aniki - Kyukyoku ... Otoko no Gyakushu",
    "Choro Q Park",
    "Chou Jikuu Yousai Macross - Ai Oboete Imasu ka",
    "Christmas NiGHTS into Dreams...",
    "Cleopatra Fortune",
    "ClockWerx",
    "Clockwork Knight - Pepperouchau no Daibouken Gekan",
    "Clockwork Knight - Pepperouchau no Daibouken Joukan",
    "Clockwork Knight - Pepperouchau no Fukubukuro",
    "Code R",
    "Command & Conquer",
    "Conveni - Ano Machi o Dokusen seyo",
    "Conveni 2 - Zenkoku Chain Tenkai da!",
    "Courier Crisis - The Saga of the Modern Fatalist",
    "Creature Shock",
    "Crimewave",
    "Criticom - The Critical Combat",
    "Croc! Pau-Pau Island",
    "Cross Romance - Ai to Mahjong to Hanafuda to",
    "Cross Tantei Monogatari - Motsureta Nanatsu no Labyrinth",
    "Crows - The Battle Action for SegaSaturn",
    "Cube Battler - Story of Anna",
    "Cube Battler - Story of Shou",
    "Cubic Gallery - Edy & Disy",
    "Culdcept",
    "Cyber Doll",
    "Cyberbots - Fullmetal Madness",
    "Cyberia",
    "D no Shokutaku",
    "D-Xhird",
    "DJ Wars",
    "DX Jinsei Game - The Game of Life",
    "DX Jinsei Game II",
    "DX Nippon Tokkyuu Ryokou Game - Let's Travel in Japan",
    "Daibouken - Great Adventure - St. Elmos no Kiseki",
    "Daikoukai Jidai Gaiden",
    "Daikoukai Jidai II",
    "Daisenryaku - Strong Style",
    "Daisuki",
    "Daitoride",
    "Darius Gaiden",
    "Darius II",
    "Dark Hunter Ge - Youma no Mori",
    "Dark Hunter Jou - Ijigen Gakuen",
    "Dark Savior",
    "Dark Seed II",
    "Darkseed",
    "Daytona USA - Circuit Edition",
    "Daytona USA",
    "DeJig - Aqua World",
    "DeJig - Lassen - Art Collection",
    "DeJig - McKnight - Art Collection",
    "DeJig - Tin Toy",
    "Dead or Alive",
    "Deadalus",
    "Death Crimson",
    "Death Throttle - Kakuzetsu Toshi kara no Dasshutsu",
    "DeathMask",
    "DecAthlete for SegaNet",
    "DecAthlete",
    "Decathlete For SegaNet(Japan)",
    "Deep Fear",
    "Defcon 5",
    "Deka Yonku - Tough the Truck",
    "Delisoba Deluxe",
    "Dennou Senki - Virtual On - Cyber Troopers for SegaNet",
    "Dennou Senki - Virtual On - Cyber Troopers",
    "Denpa Shounen-teki Game",
    "Densetsu no Ogre Battle",
    "Densha de Go! EX",
    "Derby Analyst",
    "Derby Stallion",
    "Deroon Dero Dero",
    "Desire",
    "Destruction Derby",
    "Detana Twinbee Yahoo! Deluxe Pack",
    "Device Reign",
    "Devil Summoner - Soul Hackers - Akuma Zensho Dai-ni-shuu",
    "Devil Summoner - Soul Hackers",
    "Dezaemon 2",
    "Die Hard Trilogy",
    "Digital Ange - Dennou Tenshi SS",
    "Digital Dance Mix Vol. 1 - Namie Amuro",
    "Digital Monster Ver. S - Digimon Tamers",
    "Digital Pinball - Last Gladiators",
    "Digital Pinball - Necronomicon",
    "Dino Island - Yokoku-hen",
    "Dino Island",
    "Discworld",
    "DoDonPachi",
    "DonPachi",
    "Doom",
    "Doraemon - Nobita to Fukkatsu no Hoshi",
    "Doukoku Soshite...",
    "Doukyuusei - if",
    "Doukyuusei 2",
    "Dragon Ball Z - Idainaru Dragon Ball Densetsu",
    "Dragon Ball Z - Shinbutouden",
    "Dragon Force II - Kami Sarishi Daichi ni",
    "Dragon Force",
    "Dragon Master Silk",
    "Dragon's Dream",
    "Dream Square - Hinagata Akiko",
    "Drift King Shutokou Battle '97 - Tsuchiya Keiichi & Bandou Masaaki",
    "Druid - Yami e no Tsuiseki-sha",
    "Dungeon Master Nexus",
    "Dungeons & Dragons Collection",
    "Dynamite Deka",
    "EGWord Ver 2.00",
    "Earthworm Jim 2",
    "Eberouge Special - Koi to Mahou no Gakuen Seikatsu",
    "Eberouge",
    "Eisei Meijin II",
    "Eisei Meijin",
    "Eiyuu Shigan - Gal Act Heroism",
    "Elevator Action^2 - Returns",
    "Elf o Karu Monotachi - Hanafuda-hen",
    "Elf o Karu Monotachi II",
    "Elf o Karu Monotachi",
    "Emit Vol. 1 - Toki no Maigo",
    "Emit Vol. 2 - Inochigake no Tabi",
    "Emit Vol. 3 - Watashi ni Sayonara o",
    "Enemy Zero",
    "Eternal Melody",
    "Etude Prologue - Yureugoku Kokoro no Katachi",
    "Eve - Burst Error",
    "Eve - The Lost One",
    "Eyeful Home",
    "F-1 Live Information",
    "FEDA Remake! The Emblem of Justice",
    "FIFA Soccer 96",
    "Falcom Classics (Japan)",
    "Falcom Classics II",
    "Fantastep",
    "Farland Saga - Toki no Michishirube",
    "Farland Saga",
    "Farland Story - Habou no Mai",
    "Father Christmas",
    "Fighter's History Dynamite",
    "Fighters Megamix",
    "Fighting Vipers",
    "Final Fight Revenge",
    "Find Love 2 - Rhapsody",
    "Find Love 2 - The Prologue",
    "Fire Pro Gaiden Blazing Tornado",
    "Fire Prowrestling S - 6Men Scramble",
    "Fishing Koushien II",
    "Fishing Koushien",
    "Fist",
    "Formula Grand Prix - Team Un'ei Simulation",
    "Frank Thomas Big Hurt Baseball",
    "Free Talk Studio - Mari no Kimamana Oshaberi",
    "Friends - Seishun no Kagayaki",
    "From TV Animation Slam Dunk - I Love Basketball",
    "Full Cowled Mini Yonku - Super Factory",
    "Fully Cowled Mini Yonku - Super Factory",
    "Funky Fantasy",
    "Funky Head Boxers Plus",
    "Funky Head Boxers",
    "Fushigi no Kuni no Angelique",
    "Fuusui Sensei - Feng-Shui Master",
    "G Vector",
    "GT24",
    "Gaia Breeder",
    "Gakkou no Kaidan",
    "Gakkou no Kowai Uwasa - Hanako-san ga Kita!!",
    "Gal Jan",
    "Galaxy Fight - Universal Warriors",
    "Gale Racer",
    "Gals Panic SS",
    "Game Basic for SegaSaturn",
    "Game Nihonshi - Kakumeiji Oda Nobunaga",
    "Game Tengoku - The Game Paradise!",
    "Game de Seishun",
    "Game no Tatsujin 2",
    "Game no Tatsujin",
    "Game no Tetsujin - The Shanghai",
    "Game-Ware Vol. 1",
    "Game-Ware Vol. 2",
    "Game-Ware Vol.3",
    "Game-Ware Vol.4",
    "Game-Ware Vol.5",
    "Garou Densetsu 3 - Road to the Final Victory",
    "GeGeGe no Kitarou - Gentou Kaikitan",
    "Gebockers",
    "Gekiretsu Pachinkers",
    "Gekirindan",
    "Gekitotsu Koushien",
    "Gekka Mugentan Torico",
    "Gekka no Kishi - Ouryuu-sen",
    "Gensou Suikoden",
    "Gex",
    "Ghen War",
    "Ginga Eiyuu Densetsu Plus",
    "Ginga Eiyuu Densetsu",
    "Ginga Ojousama Densetsu Yuna - Mika Akitaka Illust Works 2",
    "Ginga Ojousama Densetsu Yuna - Mika Akitaka Illust Works",
    "Ginga Ojousama Densetsu Yuna 3 - Lightning Angel",
    "Ginga Ojousama Densetsu Yuna Remix",
    "Girl Doll Toy - Tamashii o Kudasai",
    "Girls in Motion Puzzle Vol. 1 - Hiyake no Omoide + Himekuri",
    "Girls in Motion Puzzle Vol. 2 - Body Special 264",
    "Go III Professional - Taikyoku Igo",
    "Godzilla - Rettou Shinkan",
    "Goiken Muyou - Anarchy in the Nippon",
    "Gokujou Parodius Da! Deluxe Pack",
    "Golden Axe - The Duel",
    "Gotha - Ismailia SenEki",
    "Gotha II - Tenkuu no Kishi",
    "Gouketsuji Ichizoku 3 - Groove on Fight",
    "Gradius Deluxe Pack",
    "Gran Chaser",
    "GranDread",
    "Grandia - Digital Museum",
    "Grandia - Prelude",
    "Grandia",
    "Greatest Nine '96",
    "Grid Runner",
    "Guardian Force",
    "Guardian Heroes",
    "GunBlaze-S",
    "Gunbird",
    "Gungriffon - The Eurasian Conflict",
    "Gungriffon II",
    "Gussun Oyoyo S",
    "Gyuwambler Jiko Chuushinha - Tokyo Mahjongland",
    "Habitat II",
    "Hang On GP '95",
    "Hansha de Spark!",
    "Harukaze Sentai V-Force",
    "HatTrick Hero S",
    "Hatsukoi Monogatari",
    "Haunted Casino",
    "Heartbeat Scramble",
    "Heisei Tensai Bakabon - Susume! Bakabons",
    "Heiwa Pachinko Soushingeki",
    "Henry Explorers",
    "Hexen - Beyond Heretic",
    "Hi-Octane",
    "Hideo Nomo World Series Baseball",
    "Highschool Terra Story",
    "Himitsu Sentai Metamor V",
    "Hissatsu Pachinko Collection",
    "Hissatsu!",
    "Hokuto no Ken",
    "Honkaku 4-nin Uchi Geinoujin Taikyoku Mahjong - The Wareme de Pon",
    "Honkaku Hanafuda",
    "Honkaku Pro Mahjong - Tetsuman Special",
    "Honkaku Shougi Shinan - Wakamatsu Shougi Juku",
    "Hop Step Idol",
    "Horde",
    "Horror Tour",
    "Houkago Ren'ai Club - Koi no Etude",
    "Houma Hunter Lime Perfect Collection",
    "House of the Dead",
    "Hudson Soft - New Soft Line Up for Sega Saturn",
    "Hyper 3D Pinball",
    "Hyper Duel",
    "Hyper Golf - Devil's Course",
    "Hyper Reverthion",
    "Hyper Securities S",
    "I Love Donald Duck Guruzia Ou no Hihou",
    "Ide Yousuke Meijin no Shin Jissen Mahjong",
    "Idol Janshi Suchie-Pai II",
    "Idol Janshi Suchie-Pai Mecha Genteiban - Hatsubai 5 Shuunen Toku Package",
    "Idol Janshi Suchie-Pai Remix",
    "Idol Janshi Suchie-Pai Secret Album",
    "Idol Janshi Suchie-Pai Special",
    "Idol Mahjong Final Romance 2",
    "Idol Mahjong Final Romance R",
    "Impact Racing",
    "Initial D - Koudou Saisoku Densetsu",
    "Interactive Movie Action - Thunder Storm & Road Blaster (Japan)",
    "Ippatsu Gyakuten - Gambling King e no Michi",
    "Irem Arcade Classics",
    "Iron Man & X-O Manowar in Heavy Metal",
    "Ishin no Arashi",
    "Isto E Zico - Zico no Kangaeru Soccer",
    "J. B. Harold - Blue Chicago Blues",
    "J. League Go Go Goal!",
    "J. League Jikkyou Honoo no Striker",
    "J. League Pro Soccer Club o Tsukurou! 2",
    "J. League Pro Soccer Club o Tsukurou!",
    "J. League Victory Goal '96",
    "J. League Victory Goal '97",
    "Jantei Battle Cos-Player - Original Genga-shuu",
    "Jantei Battle Cos-Player",
    "Japan Super Bass Classic '96",
    "Jikkyou Oshaberi Parodius - Forever with Me",
    "Jikkyou Powerful Pro Yakyuu '95 - Kaimakuban",
    "Jikkyou Powerful Pro Yakyuu S",
    "Jikuu Tantei DD (Dracula Detective) - Maboroshi no Lorelei",
    "Jinzou Ningen Hakaider - Last Judgement",
    "Jissen Mahjong",
    "Jissen Pachinko Hisshou-hou! Twin",
    "Jissen! Pachi-Slot Hisshou-hou! 3",
    "Jissen! Pachi-Slot Hisshou-hou! 4",
    "Jissen! Pachi-Slot Hisshou-hou! Iron Hook - The Great Marine Adventures",
    "Johnny Bazooka",
    "Joshikousei no Houkago... Pukunpa",
    "Junclassic C.C. & Rope Club",
    "Jung Rhythm",
    "Jungle Park - Saturn Shima",
    "K-1 Grand Prix - Fighting Illusion Shou",
    "Kaitei Daisensou",
    "Kaitou Saint Tail",
    "Kakinoki Shougi",
    "Kakyuusei",
    "Kamen Rider - Sakusen File 1",
    "Kanazawa Shougi",
    "Kanzen Chuukei Pro Yakyuu Greatest Nine",
    "Keiou Yuugekitai - Katsugeki-hen",
    "Kekkon - Marriage - Zen'ya",
    "Kekkon - Marriage",
    "Keriotosse!",
    "Kidou Senkan Nadesico - The Blank of 3 Years",
    "Kidou Senkan Nadesico - Yappari Saigo wa Ai ga Katsu",
    "Kidou Senshi Gundam - Gihren no Yabou - Kouryaku Shireisho",
    "Kidou Senshi Gundam - Gihren no Yabou",
    "Kidou Senshi Z Gundam - Kouhen Uchuu o Kakeru",
    "Kidou Senshi Z Gundam - Zenpen Zeta no Kodou",
    "Kindaichi Shounen no Jikenbo - Hoshimitou Kanashimi no Fukushuuki",
    "King of Boxing",
    "King of Fighters '95",
    "King of Fighters '96",
    "King of Fighters '97",
    "Kiss yori...",
    "Kisuishou Densetsu Astal",
    "Kochira Katsushikaku Kameari Kouenmae - Hashutsujo - Nakagawa Land Dai-Race! no Maki",
    "Koden Koureijutsu - Hyaku Monogatari - Honto ni Atta Kowai Hanashi (Japan)",
    "Koi no Summer Fantasy - in Miyazaki Seagaia",
    "Konami Antiques - MSX Collection Ultra Pack",
    "Kouryuu Sangoku Engi",
    "Krazy Ivan",
    "Kumitate Battle Kuttu Ketto",
    "Kunoichi Torimonochou",
    "Kuro no Danshou - The Literary Fragment",
    "Kurubushi Kyoudai Gekijou Dai-ikkan - Mahjong-hen",
    "Kururin Pa!",
    "Kuusou Kagaku Sekai Gulliver Boy",
    "Kyuukyoku Tiger II Plus",
    "Kyuutenkai",
    "Langrisser - Dramatic Edition",
    "Langrisser III",
    "Langrisser IV",
    "Langrisser Tribute",
    "Langrisser V - The End of Legend",
    "Last Bronx",
    "Layer Section II",
    "Layer Section",
    "Legend of Heroes I & II - Eiyuu Densetsu",
    "Legend of K-1 - Grand Prix '96",
    "Legend of K-1 - The Best Collection",
    "Lifescape - Seimei 40 Okunen Haruka na Tabi (Japan)",
    "Lifescape 2 - Body Bionics - Kyoui no Shouuchuu Jintai",
    "Linda^3 Kanzenban",
    "Linkle Liver Story",
    "Lode Runner - The Legend Returns",
    "Lode Runner Extra",
    "Logic Puzzle - Rainbow Town",
    "Lost World - Jurassic Park",
    "Lovely Pop 2 in 1 - Jan Jan Koi Shimasho",
    "LuLu - Un Conte Interactif de Romain Victor-Pujebet",
    "Lunar - Silver Star Story Complete",
    "Lunar - Silver Star Story",
    "Lunar 2 - Eternal Blue",
    "Lupin Sansei - Pyramid no Kenja",
    "Lupin the 3rd - The Master File",
    "Lupin the 3rd Chronicles",
    "Maboroshi no Black Bass",
    "Madou Monogatari",
    "Magic Carpet",
    "Magic Knight Rayearth",
    "Magical Drop 2",
    "Magical Drop III - Toretate Zoukangou!",
    "Magical Drop",
    "Magical Hoppers",
    "Magical Night Dreams - Cotton 2",
    "Magical Night Dreams - Cotton Boomerang",
    "Mahjong Doukyuusei Special",
    "Mahjong Gakuensai DX - Zenjitsu ni Matsuwaru Funsenki",
    "Mahjong Gakuensai",
    "Mahjong Ganryuujima",
    "Mahjong Gokuu Tenjiku",
    "Mahjong Hyper Reaction R",
    "Mahjong Kaigan Monogatari - Mahjong-kyou Jidai Sexy Idol-hen",
    "Mahjong Taikai II Special",
    "Mahjong-kyou Jidai Cebu Island '96",
    "Mahjong-kyou Jidai Cogal Houkago-hen",
    "Mahou Gakuen Lunar!",
    "Mahou Shoujo Pretty Samy - Heart no Kimochi",
    "Mahou Shoujo Pretty Samy - Osorubeshi Shintai Sokutei! Kakubakuhatsu 5-Byou-mae!!",
    "Mahou no Janshi - Poe Poe Poemy",
    "Mahoutsukai ni Naru Houhou",
    "Mainichi Kawaru Quiz Bangumi - Quiz 365",
    "Manx TT SuperBike",
    "Maria - Kimi-tachi ga Umareta Wake",
    "Marica - Shinjitsu no Sekai",
    "Marie no Atelier Ver. 1.3 - Salburg no Renkinjutsushi",
    "Mario Mushano no Chou Shougi Juku - Mario Mushano's Hyper Shogi School",
    "Marvel Super Heroes vs. Street Fighter",
    "Marvel Super Heroes",
    "Mass Destruction - Otousan ni mo Dekiru Soft",
    "Master of Monsters - Neo Generations",
    "Masters - Harukanaru Augusta 3",
    "Matsukata Hiroki no World Fishing",
    "MechWarrior 2",
    "Mechanical Violator Hakaider - Last Judgement",
    "MediaROMancer - DA - Daisuke Asakura",
    "MeltyLancer - Ginga Shoujo Keisatsu 2086",
    "Message Navi Vol. 2",
    "Message Navi",
    "Metal Black",
    "Metal Fighter Miku",
    "Metal Slug - Super Vehicle-001",
    "Mezase Idol Star!! Natsuiro Memories - Mahjong-hen",
    "Mighty Hits",
    "Minakata Hakudou Toujou",
    "Minami no Shima ni Buta ga Ita - Lucas no Daibouken",
    "Minton Keibu no Sousa File - Doukeshi Satsujin Jiken",
    "Mizubaku Daibouken",
    "Mizuki Shigeru no Youkai Zukan Soushuuhen",
    "Mobile Suit Gundam Side Story I - Senritsu no Blue",
    "Mobile Suit Gundam Side Story II - Ao o Uketsugu Mono",
    "Mobile Suit Gundam Side Story III - Sabakareshi Mono",
    "Mobile Suit Gundam",
    "Moero!! Pro Yakyuu '95 - Double Header",
    "Momotarou Douchuuki",
    "Monster Slider",
    "Moon Cradle",
    "Mortal Kombat II Kanzenban",
    "Motteke Tamago with Ganbare! Kamonohashi",
    "Moujiya",
    "Mouri Motonari - Chikai no Sanshi",
    "Mr. Bones",
    "Mujintou Monogatari R - Futari no Love Love Island",
    "Murakoshi Seikai no Bakuchou Nihon Rettou",
    "My Best Friends - St. Andrew Jogakuin-hen",
    "My Dream - On Air ga Matenakute",
    "My Fair Lady - Virtual Mahjong II",
    "Myst",
    "NBA Jam - Tournament Edition",
    "NBA Jam Extreme",
    "NFL Quarterback Club '96",
    "NFL Quarterback Club '97",
    "NHL 97",
    "NHL Powerplay '96",
    "NOeL 3 - Not Digital",
    "Nanatsu Kaze no Shima Monogatari",
    "Nanatsu no Hikan",
    "Nekketsu Oyako",
    "Neon Genesis - Evangelion - Koutetsu no Girlfriend",
    "Neon Genesis Evangelion - Digital Card Library",
    "Next King - Koi no Sennen Oukoku",
    "NiGHTS into Dreams...",
    "Night Striker S",
    "Nightruth - Explanation of the Paranormal - Futatsu Dake no Shinjitsu",
    "Nightruth - Explanation of the Paranormal - Making of Nightruth II - Voice Selection",
    "Nightruth - Explanation of the Paranormal - Maria",
    "Nightruth - Explanation of the Paranormal - Nightruth Voice Selection - Radio Drama-hen",
    "Nightruth - Explanation of the Paranormal - The Making of Nightruth",
    "Nightruth - Explanation of the Paranormal 01 - Yami no Tobira",
    "Nihon Daihyou Team no Kantoku ni Naruu! Sekaihatsu Soccer RPG",
    "Nihon Pro Mahjong Renmei Kounin - Doujou Yaburi",
    "Nile-gawa no Yoake",
    "Ninja Jajamaru-kun - Onigiri Ninpouchou Gold",
    "Ninkuu - Tsuyokina Yatsura no Daigekitotsu!",
    "Ninpen Manmaru",
    "Nissan Presents - Over Drivin' GT-R",
    "No-appointment Gals Olympos",
    "Nobunaga no Yabou - Shouseiroku",
    "Nobunaga no Yabou Returns",
    "Nobunaga no Yabou Sengoku Gunyuuden",
    "Nobunaga no Yabou Tenshouki with Power-Up Kit",
    "Nobunaga no Yabou Tenshouki",
    "Nonomura Byouin no Hitobito",
    "Noon",
    "Ochigee Designer Tsukutte Pon!",
    "Off-World Interceptor Extreme",
    "Ojousama Express",
    "Ojousama o Nerae!!",
    "Okudera Yasuhiko no Sekai o Mezase! Soccer Kids - Nyuumon-hen",
    "Olympic Soccer",
    "Omakase! Savers",
    "Ooedo Renaissance",
    "Oracle no Houseki - Jewels of the Oracle",
    "Ou-chan no Oekaki Logic",
    "Ousama Game",
    "PD Ultraman Link",
    "PGA Tour 97",
    "Pachinko Hall - Shinsou Daikaiten",
    "Pad Nifty 1.1 & Habitat II",
    "Pad Nifty",
    "Paneltia Story - Koeln no Daibouken",
    "Panic-chan",
    "Panzer Dragoon II Zwei",
    "Panzer Dragoon",
    "Pappara Paoon",
    "Pastel Muses",
    "Pebble Beach Golf Links - Stadler ni Chousen",
    "PhantasM",
    "Photo Genic",
    "Photograph of a Crime - Hankou Shashin - Shibarareta Shoujo-tachi no Mita Mono wa",
    "Pia Carrot e Youkoso!! 2",
    "Pia Carrot e Youkoso!! We've Been Waiting for You",
    "PictFlash Don Don",
    "Pinball Graffiti",
    "Planet Joker",
    "Playboy - Karaoke Collection Volume 1",
    "Playboy - Karaoke Collection Volume 2",
    "Pocket Fighter",
    "Policenauts",
    "Popoitto Hebereke",
    "PriCla (Princess Clara) Daisakusen",
    "Primal Rage",
    "Princess Crown",
    "Princess Maker - Yumemiru Yousei",
    "Princess Maker 2",
    "Princess Quest",
    "Prisoner of Ice - Jashin Kourin",
    "Private Idol Disc - Data-hen - Race Queen F",
    "Private Idol Disc - Data-hen - Race Queen G",
    "Private Idol Disc - Tokubetsu-hen - Can Gal '97",
    "Private Idol Disc - Tokubetsu-hen - Cosplayers",
    "Private Idol Disc - Tokubetsu-hen - Kogal Daihyakka 100",
    "Private Idol Disc Vol. 1 - Yuu Kinoshita",
    "Private Idol Disc Vol. 10 - Mai Masaki",
    "Private Idol Disc Vol. 11 - Mayumi Hirose",
    "Private Idol Disc Vol. 2 - Miki Uchiyama",
    "Private Idol Disc Vol. 3 - Akemi Ooshima",
    "Private Idol Disc Vol. 4 - Mirei Kuroda",
    "Private Idol Disc Vol. 5 - Nanako Fujisaki",
    "Private Idol Disc Vol. 6 - Satomi Yoshida",
    "Private Idol Disc Vol. 7 - Kaori Asou",
    "Private Idol Disc Vol. 8 - Emiko Furukawa",
    "Private Idol Disc Vol. 9 - Keiko Nagamatsu",
    "Pro Mahjong Kiwame-S",
    "Pro Shinan Mahjong - Tsuwamono",
    "Pro Yakyuu Greatest Nine '97 - Make Miracle",
    "Pro Yakyuu Greatest Nine '97",
    "Pro Yakyuu Greatest Nine '98 - Summer Action",
    "Pro Yakyuu Greatest Nine '98",
    "Pro Yakyuu Team mo Tsukurou!",
    "Psychotron",
    "Pup-Breeder",
    "Puyo Puyo Sun for SegaNet",
    "Puyo Puyo Sun",
    "Puyo Puyo Tsuu",
    "Puzzle Bobble 2X",
    "Puzzle Bobble 3 - For SegaNet",
    "Puzzle Bobble 3",
    "Pyon Pyon Kyaruru no Mahjong Hiyori",
    "Quantum Gate I - Akumu no Joshou",
    "Quiz Nanairo Dreams - Nijiirochou no Kiseki",
    "QuoVadis 2 - Wakusei Kyoushuu Ovan Rei",
    "QuoVadis",
    "RMJ - The Mystery Hospital",
    "Rabbit",
    "Race Drivin'",
    "Radiant Silvergun",
    "Rampo",
    "Rapyulus Panic",
    "Rayman",
    "Real Bout Garou Densetsu Special",
    "Real Bout Garou Densetsu",
    "Real Mahjong Adventure Umi e - Summer Waltz",
    "Real Sound - Kaze no Regret",
    "Refrain Love - Anata ni Aitai",
    "Return to Zork",
    "Revolution X - Music Is the Weapon",
    "Riglordsaga 2",
    "Riglordsaga",
    "Rise 2 - Resurrection",
    "Riven - The Sequel to Myst",
    "RoX - 6 = Six",
    "Road Rash",
    "Robo Pit",
    "Rockman 8 - Metal Heroes",
    "Rockman X3",
    "Rockman X4",
    "Ronde",
    "Roommate - Inoue Ryouko",
    "Roommate - Ryouko in Summer Vacation",
    "Roommate 3 - Ryouko Kaze no Kagayaku Asa ni",
    "Roommate W - Futari",
    "Ruriiro no Yuki",
    "Ryougae Puzzle Game Moudjiya",
    "Ryouko no Oshaberi Room",
    "Ryouri no Tetsujin - Kitchen Stadium Tour",
    "Ryuuteki Gosennen - Dragons of China",
    "SD Gundam - GCentury S",
    "Sakamoto Ryouma - Ishin Kaikoku",
    "Sakura Taisen - Hanagumi Taisen Columns",
    "Sakura Taisen - Hanagumi Tsuushin",
    "Sakura Taisen - Jouki Radio Show",
    "Sakura Taisen - Teigeki Graph",
    "Sakura Taisen 2 - Kimi, Shinitamou Koto Nakare",
    "Sakura Taisen",
    "Sakura Tsuushin",
    "Salamander Deluxe Pack Plus",
    "Samurai Spirits - Amakusa Kourin",
    "Samurai Spirits - Zankurou Musouken",
    "Sangokushi Eiketsuden",
    "Sangokushi IV with Power-Up Kit",
    "Sangokushi IV",
    "Sangokushi Koumeiden",
    "Sangokushi Returns",
    "Sangokushi V",
    "Sankyo Fever - Jikki Simulation S Vol. 2",
    "Sankyo Fever - Jikki Simulation S Vol. 3",
    "Sankyo Fever - Jikki Simulation S",
    "SatMag Sono CD",
    "Saturn Bomberman Fight!!",
    "Saturn Bomberman",
    "Saturn CG Selection Vol. 1",
    "Saturn Music School 2",
    "Saturn Music School",
    "Saturn Super Henshuubu Hen - Taikenban Saturn Soft Taizen",
    "Savaki",
    "SeaBass Fishing 2",
    "SeaBass Fishing",
    "Sega Ages - After Burner II",
    "Sega Ages - Columns Arcade Collection",
    "Sega Ages - Fantasy Zone",
    "Sega Ages - Galaxy Force II",
    "Sega Ages - Memorial Selection Vol. 1",
    "Sega Ages - Memorial Selection Vol. 2",
    "Sega Ages - OutRun",
    "Sega Ages - Phantasy Star Collection",
    "Sega Ages - Power Drift",
    "Sega Ages - Rouka ni Ichidanto R",
    "Sega Ages - Shukudai ga Tanto R",
    "Sega Ages - Space Harrier",
    "Sega International Victory Goal",
    "Sega Rally Championship Plus",
    "Sega Rally Championship",
    "Sega Saturn de Hakken!! Tamagotchi Park",
    "Sega Touring Car Championship",
    "Sega Worldwide Soccer '98",
    "SegaSaturn Internet Vol. 1",
    "Segata Sanshirou - Shinken Yuugi",
    "Seifuku Densetsu - Pretty Fighter X",
    "Seikai Risshiden - Yoi Kuni, Yoi Seiji",
    "Seireki 1999 - Pharaoh no Fukkatsu",
    "Sekai no Shasou kara - I Swiss-hen - Alps Tozantetsudou no Tabi",
    "Sengoku Blade - Sengoku Ace Episode II",
    "Senken Kigyouden",
    "Senkutsu Katsuryu Taisen - Chaos Seed",
    "Senryaku Shougi",
    "Sentimental Graffiti - First Window",
    "Sentimental Graffiti",
    "Sento Monogatari Sono I",
    "Sexy Parodius",
    "Shadows of the Tusk",
    "Shanghai - Banri no Choujou - The Great Wall",
    "Shanghai - Great Moments",
    "She'sn",
    "Shellshock - Jus' Keepin' da Peace",
    "Shichisei Toushin Guyferd - Crown Kaimetsu Sakusen",
    "Shichuu Suimei Pitagraph",
    "Shienryuu",
    "Shin Kaitei Gunkan - Koutetsu no Kodoku",
    "Shin Megami Tensei - Devil Summoner - Akuma Zensho",
    "Shin Megami Tensei - Devil Summoner",
    "Shin Seiki Evangelion - 2nd Impression",
    "Shin Seiki Evangelion - Eva to Yukaina Nakama-tachi",
    "Shin Seiki Evangelion",
    "Shin Shinobi Den",
    "Shin Theme Park",
    "Shingata Kururin Pa!",
    "Shining Force III - Scenario 1 - Outo no Kyoshin",
    "Shining Force III - Scenario 2 - Nerawareta Miko",
    "Shining Force III - Scenario 3 - Hyouheki no Jashinguu",
    "Shining Force III Premium Disc",
    "Shining Wisdom",
    "Shining the Holy Ark",
    "Shinouken",
    "Shinpi no Sekai - El-Hazard",
    "Shinrei Jusatsushi Taroumaru",
    "Shinsetsu Samurai Spirits - Bushidou Retsuden",
    "Shinsetsu Yumemi Yakata - Tobira no Oku ni Darekaga...",
    "Shippuu Mahou Daisakusen - Kingdom-Grandprix",
    "Shiroki Majo - Mou Hitotsu no Eiyuu Densetsu",
    "Shougi Matsuri",
    "Shoujo Kakumei Utena - Itsuka Kakumei Sareru Monogatari",
    "Shouryuu Sangoku Engi",
    "Shunsai",
    "Shusse Mahjong Daisettai",
    "Sid Meier's Civilization - Shin Sekai Shichidai Bunmei",
    "Side Pocket 2 - Densetsu no Hustler",
    "Side Pocket 3",
    "Silhouette Mirage",
    "SimCity 2000",
    "Simulation RPG Tkool",
    "Simulation Zoo",
    "Skull Fang - Kuuga Gaiden",
    "Sky Target",
    "Slam 'n Jam '96 featuring Magic & Kareem",
    "Slayers Royal 2",
    "Slayers Royal",
    "Snatcher",
    "Soeldnerschild",
    "Sokkou Seitokai - Sonic Council",
    "Sol Divide",
    "Solo Crisis",
    "Sonic 3D - Flickies' Island",
    "Sonic Jam",
    "Sonic R",
    "Sonic Wings Special",
    "Sotsugyou Album",
    "Sotsugyou Crossworld",
    "Sotsugyou II - Neo Generation",
    "Sotsugyou III - Wedding Bell",
    "Sotsugyou S - Graduation S",
    "Soukuu no Tsubasa - Gotha World",
    "Soukyuu Gurentai - Otokuyou",
    "Soukyuu Gurentai",
    "Sound Novel Machi",
    "Sound Novel Tkool 2",
    "Sound Qube",
    "Soviet Strike",
    "Space Invaders",
    "Space Jam",
    "Spot Goes to Hollywood",
    "Stakes Winner - GI Kanzen Seiha e no Michi",
    "Stakes Winner 2 - Saikyouba Densetsu",
    "Standby Say You!",
    "Star Bowling Vol. 2",
    "Star Bowling",
    "StarFighter 3000",
    "Steam-Heart's",
    "Steamgear Mash",
    "Steeldom",
    "Steep Slope Sliders",
    "Stellar Assault SS",
    "Strahl - Himerareshi Nanatsu no Hikari",
    "Street Fighter - Real Battle on Film",
    "Street Fighter Collection",
    "Street Fighter II Movie",
    "Street Fighter Zero 2'",
    "Street Fighter Zero 2",
    "Street Fighter Zero 3",
    "Street Fighter Zero",
    "Street Racer Extra",
    "Striker '96 (En,Fr,De,Es,It)",
    "Strikers 1945 II",
    "Strikers 1945",
    "Suchie-Pai Adventure - Doki Doki Nightmare",
    "Sugoventure - Dragon Master Silk Gaiden",
    "Suiko Enbu - Fuuun Saiki",
    "Suiko Enbu",
    "Suikoden - Tendou Hyaku Hachi-sei",
    "Suikoden - Tenmei no Chikai",
    "Super Adventure Rockman (Episode 3 - Saigo no Tatakai!!)",
    "Super Casino Special",
    "Super Puzzle Fighter II X",
    "Super Real Mahjong Graffiti (P's Club Special Edition)",
    "Super Real Mahjong P7 (P's Club Special Edition)",
    "Super Real Mahjong PV (P's Club Special Edition)",
    "Super Real Mahjong PVI (P's Club Special Edition)",
    "Super Robot Taisen F Kanketsuhen",
    "Super Robot Taisen F",
    "Super Tempo",
    "Sword & Sorcery",
    "Tactical Fighter",
    "Tactics Formula",
    "Tactics Ogre - Let Us Cling Together",
    "Tadaima Wakusei Kaitaku-chuu!",
    "Taiheiyou no Arashi 2 - 3D Heiki Data-shuu",
    "Taiheiyou no Arashi 2 - Shippuu no Moudou",
    "Taikou Risshiden II",
    "Taikyoku Shougi - Kiwame II",
    "Taito Chase H.Q. + S.C.I.",
    "Taklamakan - Tonkou Denki",
    "Tama - Adventurous Ball in Giddy Labyrinth",
    "Tanjou S - Debut",
    "Tantei Jinguuji Saburou - Mikan no Report",
    "Tantei Jinguuji Saburou - Yume no Owari ni",
    "Techno Motor",
    "Teitoku no Ketsudan II",
    "Teitoku no Ketsudan III with Power-Up Kit",
    "Teitoku no Ketsudan III",
    "Tekkyuu - True Pinball",
    "Tenant Wars",
    "Tenchi Muyou! Mimiri Onsen - Yukemuri no Tabi",
    "Tenchi Muyou! Rensa Hitsuyou",
    "Tenchi Muyou! Ryououki Gokuraku CD-ROM for Sega Saturn",
    "Tenchi Muyou! Toukou Muyou - Aniraji Collection",
    "Tenchi o Kurau II - Sekiheki no Tatakai",
    "Tenga Seiha",
    "Tengai Makyou - Daiyon no Mokushiroku - The Apocalypse IV",
    "Tennis Arena",
    "Terra Cresta 3D",
    "Terra Phantastica",
    "Tetris Plus",
    "Tetris S",
    "Texthoth Ludo - Arcana Senki",
    "The Crow - City of Angels",
    "Theme Park",
    "Thor - Seireioukiden",
    "Three Dirty Dwarves",
    "Thunder Force Gold Pack 1",
    "Thunder Force Gold Pack 2",
    "Thunder Force V",
    "Thunderhawk II",
    "Tilk - Aoi Umi kara Kita Shoujo",
    "Time Bokan Series - Bokan to Ippatsu! Doronboo Kanpekiban",
    "Time Commando",
    "Time Gal & Ninja Hayate",
    "Titan Wars",
    "Tokimeki Mahjong Paradise - Koi no Tenpai Beat",
    "Tokimeki Memorial - Forever with You",
    "Tokimeki Memorial - Taisen Pazurudama",
    "Tokimeki Memorial Drama Series Vol. 1 - Nijiiro no Seishun",
    "Tokimeki Memorial Drama Series Vol. 2 - Irodori no Love Song",
    "Tokimeki Memorial Drama Series Vol. 3 - Tabidachi no Uta",
    "Tokimeki Memorial Selection - Fujisaki Shiori",
    "Tokimeki Memorial Taisen Tokkaedama",
    "Tokuso Kidoutai J-SWAT",
    "Tokyo Shadow",
    "Tomb Raiders",
    "Top Anglers - Super Fishing Big Fight 2",
    "Touge King the Spirits 2",
    "Touge King the Spirits",
    "Tournament Leader",
    "Touryuu Densetsu Elan Doree",
    "Toushinden S",
    "Toushinden URA",
    "Tower",
    "Transport Tycoon",
    "Tryrush Deppy",
    "Tsuukai!! Slot Shooting",
    "TurfWind '96 - Take Yutaka Kyousouba Ikusei Game",
    "Tutankhamen no Nazo - A.N.K.H",
    "Twinkle Star Sprites",
    "Ultraman - Hikari no Kyojin Densetsu",
    "Ultraman Zukan 2",
    "Ultraman Zukan 3",
    "Ultraman Zukan",
    "Umanari 1 Furlong Gekijou",
    "Universal Nuts",
    "Uno DX",
    "Unsolved",
    "Vampire Hunter - Darkstalkers' Revenge",
    "Vampire Savior",
    "Vandal Hearts - Ushinawareta Kodai Bunmei",
    "Vatlva",
    "Victory Goal (3A)",
    "Victory Goal Worldwide Edition",
    "Virtua Cop 2",
    "Virtua Cop",
    "Virtua Fighter (USA)",
    "Virtua Fighter 2",
    "Virtua Fighter CG Portrait Series Vol. 1 - Sarah Bryant",
    "Virtua Fighter CG Portrait Series Vol. 10 - Jeffry McWild",
    "Virtua Fighter CG Portrait Series Vol. 2 - Jacky Bryant",
    "Virtua Fighter CG Portrait Series Vol. 3 - Akira Yuki",
    "Virtua Fighter CG Portrait Series Vol. 4 - Pai Chan",
    "Virtua Fighter CG Portrait Series Vol. 5 - Wolf Hawkfield",
    "Virtua Fighter CG Portrait Series Vol. 6 - Lau Chan",
    "Virtua Fighter CG Portrait Series Vol. 7 - Shun Di",
    "Virtua Fighter CG Portrait Series Vol. 8 - Lion Rafale",
    "Virtua Fighter CG Portrait Series Vol. 9 - Kage Maru",
    "Virtua Fighter Kids (Java Tea Original)",
    "Virtua Fighter Kids",
    "Virtua Fighter Remix - SegaNet Edition",
    "Virtua Fighter Remix",
    "Virtua Fighter",
    "Virtua Photo Studio - Cameraman Simulation",
    "Virtua Racing",
    "Virtuacall S (Shokai Gentei Yobikake-kun)",
    "Virtual Casino",
    "Virtual Hydlide",
    "Virtual Kyoutei 2",
    "Virtual Kyoutei",
    "Virtual Mahjong",
    "Virtual Open Tennis",
    "Virtual Volleyball",
    "Virtual-On - Cyber Troopers For SegaNet",
    "Virus",
    "Voice Fantasia S - Ushinawareta Voice Power (Premium CD-ROM)",
    "Voice Idol Maniacs - Pool Bar Story",
    "WWF In Your House",
    "WWF WrestleMania - The Arcade Game",
    "Wachenroeder",
    "Waialae no Kiseki - Extra 36 Holes",
    "Waku Waku 7",
    "Waku Waku Monster",
    "Waku Waku Puyo Puyo Dungeon",
    "WanChai Connection",
    "Wangan Dead Heat + Real Arrange",
    "Wangan Dead Heat",
    "Wangan Trial Love",
    "WarCraft II - The Dark Saga",
    "Wara Wara Wars - Gekitou! Daigundan Battle",
    "Welcome House",
    "Whizz",
    "Willy Wombat",
    "Wing Arms - Kareinaru Gekitsuiou",
    "Winning Post 2 - Final '97",
    "Winning Post 2 - Program '96",
    "Winning Post 2",
    "Winning Post 3 - Program '98",
    "Winning Post 3",
    "Winning Post EX",
    "Winter Heat",
    "WipEout",
    "Wipeout XL",
    "With You - Mitsumeteitai",
    "Wizard's Harmony 2",
    "Wizard's Harmony",
    "Wizardry - Llylgamyn Saga",
    "Wizardry Nemesis - The Wizardry Adventure",
    "Wizardry VI & VII Complete",
    "Wolf Fang SS - Kuuga 2001",
    "World Advanced Daisenryaku - Koutetsu no Senpuu",
    "World Advanced Daisenryaku - Sakusen File",
    "World Cup France '98 - Road to Win",
    "World Cup Golf - In Hyatt Dorado Beach (En,Ja)",
    "World Evolution Soccer",
    "World Heroes Perfect",
    "World Series Baseball II",
    "Worms",
    "X Japan - Virtual Shock 001",
    "X-Men - Children of the Atom",
    "X-Men vs. Street Fighter",
    "Yakyuuken Special - Kon'ya wa 12-Kaisen!!",
    "Yellow Brick Road",
    "Yoshimoto Mahjong Club",
    "Yoshimura Shougi",
    "Yoshiyuki Sadamoto Illustrations",
    "Yu-No - Konoyo no Hate de Koi o Utau Shoujo",
    "Yumimi Mix Remix",
    "Yuukyuu Gensoukyoku 2nd Album",
    "Yuukyuu Gensoukyoku Ensemble 2",
    "Yuukyuu Gensoukyoku Ensemble",
    "Yuukyuu Gensoukyoku",
    "Yuukyuu no Kobako Official Collection",
    "Yuushun - Classic Road",
    "Zanma Chouougi Valhollian",
    "Zap! Snowboarding Trix '98",
    "Zap! Snowboarding Trix",
    "Zen Nihon Pro Wres featuring Virtua",
    "Zenkoku Seifuku Bishoujo Grand Prix - Find Love",
    "Zero Divide - The Final Conflict",
    "Zero4 Champ DooZy-J Type-R",
    "Zoku Gussun Oyoyo",
    "Zoku Hatsukoi Monogatari - Shuugaku Ryokou",
    "Zoop",
    "Zork I - The Great Underground Empire",
    "m [emu] - Kimi o Tsutaete"
]